import {createRun,runChunk,result} from '../../src/runner/run';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {overview,traceChart,thermalFrontiers} from '../../src/app/fitting-ui/trace-chart';
import old from '../fitting/fixtures/station-service-old.json' with {type:'json'};
for(const width of [1440,1024,390])test(`CD01–08 ${width} fresh defaults, literal replay, K-axis glyphs and real Worker`,async({browser},info)=>{
 const context=await browser.newContext({viewport:{width,height:1000},hasTouch:width!==1440,isMobile:width!==1440,acceptDownloads:true}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const action=async(id:string)=>{const l=page.locator(id);await l.evaluate(n=>n.scrollIntoView({block:'center'}));width===1440?await l.click():await l.tap();};
 const exportRun=async()=>{if(!await page.locator('#fit-more').evaluate(n=>(n as HTMLDetailsElement).open))await action('#fit-f3');const d=page.waitForEvent('download');await action('#fit-export-run');return JSON.parse(await readFile((await(await d).path())!,'utf8'));};
 await page.goto('/');await expect(page.locator('#fit-edition')).toContainText('0.2.5');await expect(page.locator('footer')).toContainText('интерфейс v4.8');await expect(page.getByRole('link',{name:'Legacy v1'})).toHaveCount(0);
 await expect(page.locator('#fit-vfa')).toHaveValue('250');await expect(page.locator('#fit-cruise')).toHaveValue('500');
 for(const [id,name,ref] of [['sputnik','Северин Спутник',250],['industrial-S','Демирмаш Ермак',225],['pony','Дизельный Пони',225]] as const){await page.locator('#fit-preset').selectOption(id==='industrial-S'?id+':1:D':id+':1');await expect(page.locator('.ship-passport h1')).toHaveText(name);await expect(page.locator('#fit-preset')).toHaveValue(id==='industrial-S'?id+':1:D':id+':1');await expect(page.locator('#fit-preset option[value^="'+id+':"]')).toHaveCount(id==='industrial-S'?3:1);await expect(page.locator('#fit-vfa')).toHaveValue(String(ref));await expect(page.locator('#fit-cruise')).toHaveValue(String(ref*2));}
 await expect(page.locator('#slot-payload-1')).toContainText('industrial-S');await expect(page.locator('#instance-builtin\\:laser')).toContainText('Лазер');
 await page.locator('#fit-cruise').selectOption('675');await page.locator('#fit-vfa').fill('230');await page.locator('#fit-vfa').press('Tab');await expect(page.locator('#fit-cruise')).toHaveValue('690');
 await page.locator('#fit-preset').selectOption('severin-mir:2:D');await expect(page.locator('.ship-passport h1')).toHaveText('Северин Мир');await expect(page.locator('#fit-cruise')).toHaveValue('675');
 await page.locator('#fit-cruise').selectOption('max');await page.locator('#fit-preset').selectOption('industrial-M:2:D');await expect(page.locator('#fit-cruise')).toHaveValue('max');await expect(page.locator('.ship-passport h1')).toHaveText('Демирмаш Титан');
 await page.locator('#fit-import').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...old.spec,mission:{...old.spec.mission,referenceVfaMS:500,cruiseSpeedMS:731}}))});await expect(page.locator('#fit-error')).toHaveText('');await expect(page.locator('#fit-cruise option:checked')).toHaveText('Заданный предел: 731 м/с');const literal=await exportRun();expect(literal.mission.referenceVfaMS).toBe(500);expect(literal.mission.cruiseSpeedMS).toBe(731);
 await page.locator('#fit-vfa').fill('510');await page.locator('#fit-vfa').press('Tab');await expect(page.locator('#fit-cruise')).toHaveValue('731');
 await page.locator('#fit-preset').selectOption('sputnik:1');await expect(page.locator('#fit-vfa')).toHaveValue('510');await expect(page.locator('#fit-cruise')).toHaveValue('731');await page.locator('#fit-duration').fill('2');await page.locator('#fit-distance').fill('0');await page.locator('#fit-approach').fill('0');await page.locator('#fit-speed').selectOption('20000');await action('#fit-start');await expect(page.locator('#fit-status')).toContainText('Рейс завершён');await expect(page.locator('#fit-dock-rate')).not.toHaveText('—');
 await action('#channel-details summary');await action('[data-channel-group="heat"]');await page.locator('#channel-unit').selectOption('K');await expect(page.locator('#channel-details [data-boundary-label]')).toHaveCount(4);await expect(page.locator('#channel-details svg')).toHaveAttribute('data-axis-x','180');
 const exportMeasured=async()=>{const d=page.waitForEvent('download');await action('#fit-export-result');return readFile((await(await d).path())!,'utf8');};
 const measured=await exportMeasured(),detail=page.locator('#channel-details svg');
 const frontiers=await detail.locator('[data-boundary]').evaluateAll(paths=>paths.map(p=>({id:p.getAttribute('data-boundary'),value:p.getAttribute('data-value'),line:p.getAttribute('d')})));
 await action('[data-curve="temperatureK"]');await expect(page.locator('#channel-unit')).toHaveValue('K');await expect(detail).toHaveAttribute('aria-label','Измеренные каналы: K');await expect(detail).toHaveAttribute('data-axis-x','180');await expect(detail.locator('[data-channel]')).toHaveCount(0);
 expect(await detail.locator('[data-boundary]').evaluateAll(paths=>paths.map(p=>({id:p.getAttribute('data-boundary'),value:p.getAttribute('data-value'),line:p.getAttribute('d')})))).toEqual(frontiers);
 await page.evaluate(()=>document.fonts.ready);const hiddenLabels=await detail.evaluate(svg=>[...svg.querySelectorAll<SVGTextElement>('[data-boundary-label]')].map(t=>{const b=t.getBBox();return{text:t.textContent,x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height};}));
 for(const t of hiddenLabels){expect(t.x).toBeGreaterThanOrEqual(0);expect(t.y).toBeGreaterThanOrEqual(0);expect(t.right).toBeLessThan(180);expect(t.bottom).toBeLessThanOrEqual(205);}
 for(let i=1;i<hiddenLabels.length;i++){const a=hiddenLabels[i-1],b=hiddenLabels[i];expect(a.bottom<=b.y||b.bottom<=a.y).toBe(true);}
 await action('[data-curve="temperatureK"]');await expect(detail.locator('[data-channel="temperatureK"]')).toHaveCount(1);await expect(detail).toHaveAttribute('data-axis-x','180');
 await page.locator('#channel-unit').selectOption('W');const wattIds=await page.locator('#channel-details [data-curve]').evaluateAll(buttons=>buttons.map(b=>b.getAttribute('data-curve')!));expect(wattIds.length).toBeGreaterThan(0);for(const id of wattIds)await action('[data-curve="'+id+'"]');
 await expect(detail.locator('[data-channel]')).toHaveCount(0);await expect(detail).toHaveAttribute('aria-label','Измеренные каналы: W');await expect(detail).toHaveAttribute('data-axis-x','180');await expect(detail.locator('[data-boundary-label]')).toHaveCount(0);expect(await exportMeasured()).toBe(measured);await page.locator('#channel-unit').selectOption('K');
 await info.attach('hidden-last-K-glyphs',{body:JSON.stringify({width,frontiers,hiddenLabels}),contentType:'application/json'});
 const run=createRun("axis",old.spec as any);runChunk(run,2);const fixture=result(run) as any,empty=structuredClone(fixture),disjoint=structuredClone(fixture);for(const i of empty.spec.resolvedShip.instances)i.enabled=false;const laser=disjoint.spec.resolvedShip.instances.find((i:any)=>i.enabled&&i.item.family==='mining');laser.item.gate={...laser.item.gate,low:580,workLow:600,workHigh:650,high:700};
 const figure=page.locator('.overview-charts figure').nth(1);const boxes=[];
 for(const [name,r] of [['common',fixture],['empty',empty],['disjoint',disjoint],['replay',fixture]] as const)for(const detailed of [false,true]){
 const thermal=thermalFrontiers(r),html=detailed?traceChart(r,['temperatureK'],undefined,thermal.limits,false,thermal.bands):overview(r);
 await figure.evaluate((f,{html,detailed})=>{if(detailed)f.innerHTML=html;else{const holder=document.createElement('div');holder.innerHTML=html;f.innerHTML=holder.querySelectorAll('figure')[1].innerHTML;}},{html,detailed});await page.evaluate(()=>document.fonts.ready);
 const b=await figure.locator('svg').evaluate(svg=>{const v=(svg as SVGSVGElement).viewBox.baseVal,axis=Number(svg.getAttribute('data-axis-x'));return{axis,view:{width:v.width,height:v.height},texts:[...svg.querySelectorAll('text')].map(t=>{const b=t.getBBox(),m=t.getScreenCTM()!;return{text:t.textContent,x:b.x,y:b.y,w:b.width,h:b.height,screen:parseFloat(getComputedStyle(t).fontSize)*Math.hypot(m.a,m.b),k:t.hasAttribute('data-k-axis-label')};})};});boxes.push({name,detailed,...b});
 expect(b.axis).toBeGreaterThan(40);for(const t of b.texts){expect(t.x,t.text!).toBeGreaterThanOrEqual(0);expect(t.y,t.text!).toBeGreaterThanOrEqual(0);expect(t.x+t.w,t.text!).toBeLessThanOrEqual(b.view.width);expect(t.y+t.h,t.text!).toBeLessThanOrEqual(b.view.height);expect(t.screen,t.text!).toBeGreaterThanOrEqual(12);if(t.k){expect(t.text).toMatch(/^[\d\s,.]+ K$/);expect(t.x+t.w).toBeLessThan(b.axis);}}
 for(let i=0;i<b.texts.length;i++)for(let j=i+1;j<b.texts.length;j++){const a=b.texts[i],c=b.texts[j];expect(a.x+a.w<=c.x||c.x+c.w<=a.x||a.y+a.h<=c.y||c.y+c.h<=a.y,`${name} ${a.text}/${c.text}`).toBe(true);}
 }
 expect(await page.evaluate(()=>({inner:innerWidth,doc:document.documentElement.scrollWidth,visual:visualViewport!.width}))).toEqual({inner:width,doc:width,visual:width});expect(errors).toEqual([]);await info.attach('K-axis-glyphs',{body:JSON.stringify(boxes),contentType:'application/json'});await context.close();
});
