import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import oldStation from '../fitting/fixtures/station-service-old.json' with {type:'json'};
for(const width of [1440,390])test(`MD01–06 ${width} real nine assemblies, custom/old mounts and immutable active/next/result ownership`,async({browser},info)=>{
 const context=await browser.newContext({viewport:{width,height:1000},isMobile:width===390,hasTouch:width===390,acceptDownloads:true}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const Native=Worker;(window as any).assemblyStarts=[];window.Worker=class extends Native{postMessage(m:any,...args:any[]){if(m.type==='start')(window as any).assemblyStarts.push(structuredClone(m));return(super.postMessage as any)(m,...args);}};});
 const action=async(selector:string)=>{const n=page.locator(selector);await n.evaluate(el=>el.scrollIntoView({block:'center'}));width===390?await n.tap():await n.click();};
 const field=async(id:string,value:string)=>{await page.locator(id).fill(value);await page.locator(id).press('Tab');};
 const more=async()=>{if(!await page.locator('#fit-more').evaluate(n=>(n as HTMLDetailsElement).open))await action('#fit-f3');};
 const exported=async(id:string)=>{await more();const wait=page.waitForEvent('download');await action(id);return JSON.parse(await readFile((await(await wait).path())!,'utf8'));};
 await page.goto('/');await expect(page.locator('#fit-edition')).toContainText('0.2.5');
 for(const [hull,n]of [['civilian-M',1],['severin-mir',2],['industrial-M',3],['industrial-S',3]] as const)await expect(page.locator(`#fit-preset option[value^="${hull}:"]`)).toHaveCount(n);
 const summary=[];
 for(const [id,code,capacity]of [['civilian-M:2:H','H',216],['severin-mir:2:D','D',216],['severin-mir:2:E','E',216],['industrial-M:2:D','D',240],['industrial-M:2:H','H',240],['industrial-M:2:E','E',240],['industrial-S:1:D','D',36],['industrial-S:1:H','H',36],['industrial-S:1:E','E',36]] as const){
  await page.locator('#fit-preset').selectOption(id);await expect(page.locator('#fit-preset')).toHaveValue(id);await expect(page.locator('#fit-start')).toBeEnabled();await field('#fit-duration','0.2');await field('#fit-dt','0.1');await field('#fit-distance','0');await field('#fit-approach','0');await field('#fit-service','1');await page.locator('#fit-speed').selectOption('20000');await action('#fit-start');await expect(page.locator('#fit-status')).toContainText(/завершён/i);const r=await exported('#fit-export-result');
  expect(r.status).toBe('complete');expect(r.spec.catalogVersion).toBe('ship-fitting-0.2.5');expect(r.state.timeSeconds).toBeCloseTo(.2,10);expect(r.spec.resolvedShip.cargoCapacityM3.universal+r.spec.resolvedShip.cargoCapacityM3.bulk).toBe(capacity);expect(r.spec.resolvedShip.instances.filter((i:any)=>i.item.family==='engine').map((i:any)=>i.item.propulsionType)).toEqual(Array(4).fill({D:'diesel',H:'hydrogen',E:'electric'}[code]));expect(r.state.fuelKg.diesel).toBeGreaterThanOrEqual(0);expect(r.state.fuelKg.hydrogen).toBeGreaterThanOrEqual(0);summary.push({id,time:r.state.timeSeconds,cargo:capacity,stocks:r.state.fuelKg});
 }
 // Импортированный опыт остаётся буквальным до явного выбора новой сборки.
 await more();const old={...oldStation.spec,mission:{...oldStation.spec.mission,referenceVfaMS:510,cruiseSpeedMS:731,distanceM:4321,serviceSeconds:3.25}};await page.locator('#fit-import').setInputFiles({name:'old.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});await expect(page.locator('#fit-error')).toHaveText('');expect(await exported('#fit-export-run')).toEqual(old);await page.locator('#fit-preset').selectOption('');expect(await exported('#fit-export-run')).toEqual(old);await expect(page.locator('#fit-preset')).toHaveValue('');await expect(page.locator('#fit-preset option:checked')).toContainText('Текущая');
 await page.locator('#fit-preset').selectOption('civilian-M:2:H');const next=await exported('#fit-export-run');expect(next.mission).toEqual(old.mission);expect(next.selectedWorkGroup).toEqual(['fit:payload-1','fit:payload-2']);
 // Дополнительный бак проверяет общий запас и честное обозначение пользовательского монтажа.
 await action('#slot-power-3');await page.locator('[data-candidate="tank-hydrogen-M"]').click();await action('#fit-apply');await expect(page.locator('#fit-preset')).toHaveValue('');const withTank=await exported('#fit-export-run');expect(withTank.resolvedShip.resources.hydrogen.capacityKg).toBe(4377.0845148+3647.570429);await action('[id="info-builtin:cryotank"]');await expect(page.locator('dialog')).toContainText('20%');await action('#instance-close');
 // Новый черновик B не должен менять действующий опыт и замороженное измерение A.
 await field('#fit-duration','10');await field('#fit-distance','0');await field('#fit-approach','0');await page.locator('#fit-speed').selectOption('1');await action('#fit-start');await expect.poll(async()=>{const text=await page.locator('#fit-time').innerText();return parseFloat(text.split('/')[0].replace(',','.'));}).toBeGreaterThan(0);await action('#fit-pause');await expect(page.locator('#fit-status')).toContainText('Пауза');const active=await exported('#fit-export-run');const paused=await exported('#fit-export-result');await action('#fit-freeze');const frozen=await page.locator('.ab-side-a').innerHTML();await action('[data-variant="B"][aria-pressed]' );await page.locator('#fit-preset').selectOption('severin-mir:2:E');expect(await exported('#fit-export-run')).toEqual(active);expect(await page.locator('.ab-side-a').innerHTML()).toBe(frozen);await action('[data-variant="A"][aria-pressed]' );await expect(page.locator('#fit-preset')).toHaveValue('');await page.locator('#fit-speed').selectOption('20000');await action('#fit-resume');await expect(page.locator('#fit-status')).toContainText(/завершён/i);const completed=await exported('#fit-export-result');expect(completed.runId).toBe(paused.runId);expect(completed.spec).toEqual(active);expect(await page.locator('.ab-side-a').innerHTML()).toBe(frozen);
 await page.locator('#fit-import').setInputFiles({name:'measured.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(completed))});await expect(page.locator('#fit-error')).toHaveText('');expect(await exported('#fit-export-result')).toEqual(completed);const before=await exported('#fit-export-run');const forged=structuredClone(before);forged.resolvedShip.hull.builtins=[];await page.locator('#fit-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(forged))});await expect(page.locator('#fit-error')).not.toHaveText('');expect(await exported('#fit-export-run')).toEqual(before);expect(await exported('#fit-export-result')).toEqual(completed);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(width);expect(errors).toEqual([]);await info.attach('assembly-ledger',{body:JSON.stringify({width,summary,activeRun:active.runId,frozenStatus:paused.status}),contentType:'application/json'});await context.close();
});
