import {test,expect} from '@playwright/test';
test('preset slot filtered catalog delta swap run comparison at390px',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('heading',{name:'U2 Ship Fitting'})).toBeVisible();
 await page.locator('#fit-preset').selectOption('industrial-M:3');await page.locator('#fit-slot').selectOption('payload-3');await page.locator('#fit-item').selectOption('cargo-bulk-S');await expect(page.locator('#fit-preview')).toContainText('После замены');await expect(page.locator('#fit-preview')).toContainText('-400');await page.locator('#fit-apply').click();await expect(page.locator('#fit-slots')).toContainText('навалочный');
 await page.locator('#fit-duration').fill('12');await page.locator('#fit-start').click();await expect(page.locator('#fit-status')).toContainText('Завершён');await expect(page.locator('#fit-result')).toContainText('SCU/h');await expect(page.locator('#fit-result')).toContainText('Использование добывающей оснастки');await page.locator('#fit-freeze').click();await expect(page.locator('#fit-comparison')).toContainText('A сохранён');
 await page.locator('#fit-preset').selectOption('industrial-M:1');await page.locator('#fit-start').click();await expect(page.locator('#fit-status')).toContainText('Завершён');await expect(page.locator('#fit-comparison')).toContainText('Одинаковые условия');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
test('incomplete fit and incompatible preview explain refusal; builtin and F3 source data visible',async({page})=>{
 await page.goto('/');await expect(page.locator('#fit-builtins')).toContainText('Встроено: заменить нельзя');await page.locator('#fit-slot').selectOption('march');await page.locator('#fit-all-items').check();await page.locator('#fit-item').selectOption('cargo-bulk-S');await expect(page.locator('#fit-preview')).toContainText('Семейство');await expect(page.locator('#fit-apply')).toBeDisabled();await page.locator('#fit-remove').click();await expect(page.locator('#fit-start')).toBeDisabled();await expect(page.locator('#fit-readiness')).toContainText('march');await page.locator('#fit-f3').click();await expect(page.locator('#fit-sources')).toContainText('J/(kg');await expect(page.locator('#fit-sources')).toContainText('sourceRef');
});
test('edit during run retains running revision and reset rejects late results; zero stocks warn',async({page})=>{
 await page.goto('/');await page.locator('#fit-duration').fill('43200');await page.locator('#fit-speed').selectOption('1');await page.locator('#fit-start').click();await page.locator('#fit-pause').click();await expect(page.locator('#fit-status')).toContainText('Пауза');const revision=await page.locator('#fit-running-revision').textContent();await page.locator('#fit-slot').selectOption('payload-1');await page.locator('#fit-item').selectOption('mining-industrial-S');await page.locator('#fit-apply').click();await expect(page.locator('#fit-running-revision')).toHaveText(revision!);await expect(page.locator('#fit-next-revision')).toContainText('2');await page.locator('#fit-reset').click();await page.waitForTimeout(100);await expect(page.locator('#fit-time')).toHaveText('0 s');await page.locator('#fit-charge-fraction').fill('0');await page.locator('#fit-fuel-fraction').fill('0');await expect(page.locator('#fit-readiness')).toContainText('пуст');await expect(page.locator('#fit-start')).toBeEnabled();
});
