import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const profiles = [[360,780],[780,360],[400,640],[640,400],[768,1024],[1024,768],[720,900],[900,720],[820,1230],[1230,820],[360,480],[500,780],[501,780],[700,780],[701,780],[900,780],[901,780],[1100,820],[1101,820]] as const;
const tap = async (p:Page, selector:string) => { const x=p.locator(selector);await x.evaluate(n=>n.scrollIntoView({block:'center'}));await x.tap(); };
const geometry = (p:Page) => p.evaluate(()=>{
 const rect=(s:string)=>{const r=document.querySelector(s)!.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height};};
 const header=document.querySelector('.ui-header')!;
 return {width:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,header:rect('.ui-header'),sticky:getComputedStyle(header).position==='sticky',dock:rect('.ui-controls'),conditions:rect('.lab-side > section')};
});
for(const [width,height] of profiles)test(`RC01–04 native reachable layout ${width}×${height}`,async({browser},info)=>{
 const c=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true}),p=await c.newPage(),errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));
 try{
 await p.goto('/');await expect(p.locator('#fit-edition')).toContainText('0.2.4');await p.evaluate(()=>document.fonts.ready);
 const g=await geometry(p);expect.soft(g.overflow).toBeLessThanOrEqual(1);
 if(height>width){expect.soft(g.header.height).toBeLessThanOrEqual(width<=700?148:112);expect.soft(g.dock.height).toBeLessThanOrEqual(width<=700?132:104);}
 if(height<=400)expect.soft((g.sticky?g.header.height:0)+g.dock.height).toBeLessThanOrEqual(height*.45);
 if(width===360)expect.soft(g.conditions.height).toBeLessThanOrEqual(900);if(width===820)expect.soft(g.conditions.height).toBeLessThanOrEqual(580);
 await tap(p,'#slot-payload-1');await expect(p.locator('#swap-close')).toBeFocused();
 await tap(p,'[data-candidate="cargo-bulk-S"]');
 const modal=await p.locator('#ui-dialog').evaluate(d=>{const r=(s:string)=>{const b=d.querySelector(s)!.getBoundingClientRect();return{top:b.top,bottom:b.bottom,height:b.height};};return{header:r('.dialog-header'),body:r('.dialog-body'),footer:r('.dialog-footer'),overflow:document.documentElement.scrollWidth-innerWidth};});
 expect.soft(modal.footer.height).toBeLessThanOrEqual(width<=500?116:120);expect.soft(modal.body.bottom).toBeLessThanOrEqual(modal.footer.top+1);expect.soft(modal.body.top).toBeGreaterThanOrEqual(modal.header.bottom-1);expect.soft(modal.footer.bottom).toBeLessThanOrEqual(height+1);expect.soft(modal.overflow).toBeLessThanOrEqual(1);
 const controls=await p.locator('#swap-close,#fit-apply,#fit-remove,.dialog-footer label,.filters input,.filters select').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return{id:n.id||'batch-label',w:r.width,h:r.height,font:parseFloat(getComputedStyle(n).fontSize)};}));for(const x of controls){expect.soft(x.h,x.id).toBeGreaterThanOrEqual(44);expect.soft(x.w,x.id).toBeGreaterThanOrEqual(44);expect.soft(x.font,x.id).toBeGreaterThanOrEqual(x.id.startsWith('swap-')&&x.id!=='swap-close'?16:12);}
 const numeric=await p.locator('[data-candidate="cargo-bulk-S"] .module-profile').evaluate(n=>{const w=document.createTreeWalker(n,NodeFilter.SHOW_TEXT),boxes:{y:number,h:number,text:string|null}[][]=[];while(w.nextNode()){const t=w.currentNode;if(!t.textContent?.includes('SCU'))continue;const r=document.createRange();r.selectNodeContents(t);boxes.push([...r.getClientRects()].map(b=>({y:b.y,h:b.height,text:t.textContent})));}return boxes;});expect.soft(numeric.every(bs=>bs.every(b=>Math.abs(b.y-bs[0].y)<1)),'number + SCU stays together').toBe(true);
 await tap(p,'#fit-apply');await expect(p.locator('#slot-payload-1')).toBeFocused();await expect(p.locator('#slot-payload-1')).toContainText('Навалочный');await tap(p,'#slot-payload-1');await tap(p,'#swap-close');await tap(p,'#fit-duration');await expect(p.locator('#fit-duration')).toBeFocused();
 console.log('RC_GEOMETRY',JSON.stringify({width,height,g,modal}));await info.attach('responsive-layout',{body:JSON.stringify({width,height,g,modal,controls,numeric,errors}),contentType:'application/json'});expect(errors).toEqual([]);
 }finally{await c.close().catch(()=>{});}
});
for(const [width,height] of [[360,780],[820,1230]] as const)test(`RC05–06 real Worker research and rotation ${width}`,async({browser},info)=>{
 test.setTimeout(60000);const c=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,acceptDownloads:true}),p=await c.newPage(),errors:string[]=[];p.on('pageerror',e=>errors.push(e.message));
 const action=(s:string)=>tap(p,s);
 const download=async(s:string)=>{const d=p.waitForEvent('download');await action(s);if(s==='#fit-save')await action('#fit-save-confirm');return readFile((await(await d).path())!,'utf8');};
 try{
 await p.goto('/');await action('#slot-payload-1');await action('#swap-search');await p.keyboard.type('Лазер');await p.keyboard.press('ArrowLeft');const caret=await p.locator('#swap-search').evaluate(n=>(n as HTMLInputElement).selectionStart);
 await p.setViewportSize({width:height,height:width});await expect(p.locator('#swap-search')).toHaveValue('Лазер');expect(await p.locator('#swap-search').evaluate(n=>(n as HTMLInputElement).selectionStart)).toBe(caret);await expect(p.locator('#swap-search')).toBeFocused();await action('#swap-close');
 await p.setViewportSize({width,height});await action('#slot-payload-1');await action('[data-candidate="mining-industrial-S"]');await action('#fit-apply');
 await action('#fit-save');await p.locator('#fit-save-name').fill('Длинное имя сборки для исследования');await p.setViewportSize({width:360,height:480});await expect(p.locator('#fit-save-name')).toHaveValue('Длинное имя сборки для исследования');await expect(p.locator('#fit-save-name')).toBeFocused();await action('#fit-save-cancel');await p.setViewportSize({width,height});
 for(const [id,value]of [['fit-duration','12'],['fit-distance','0'],['fit-approach','0'],['fit-service','1'],['fit-dt','.1'],['fit-target','1000']]){await p.locator('#'+id).fill(value);await p.locator('#'+id).press('Tab');}
 await p.locator('#fit-stop-policy').selectOption('first-stop');await p.locator('#fit-speed').selectOption('1');await action('#fit-start');await expect(p.locator('#fit-status')).toContainText('Выполняется');await expect.poll(()=>p.locator('#fit-time').textContent()).not.toBe('0 с / 12 с');await action('#fit-pause');await expect(p.locator('#fit-status')).toContainText('Пауза');
 expect(await p.locator('.ui-controls button:visible').evaluateAll(ns=>ns.map(n=>n.id))).toEqual(['fit-resume','fit-step','fit-cancel']);
 const checkpoint=await geometry(p);expect(checkpoint.dock.height).toBeLessThanOrEqual(width<=700?132:104);const paused=(await p.locator('#fit-time').textContent())!;await action('#fit-step');await expect(p.locator('#fit-time')).not.toHaveText(paused);await action('#fit-freeze');await expect(p.locator('#fit-comparison')).toContainText('Неизменяемый снимок');const frozenA=await p.locator('.ab-side-a').innerHTML();
 await action('#channel-details summary');await action('[data-channel-group="heat"]');await p.locator('#channel-unit').selectOption('K');await expect(p.locator('#channel-details [data-boundary-label]')).toHaveCount(4);
 const glyphs=await p.locator('#channel-details svg text').evaluateAll(ns=>ns.map(t=>{const b=(t as SVGTextElement).getBBox(),m=(t as SVGTextElement).getScreenCTM()!;return{text:t.textContent,x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,font:parseFloat(getComputedStyle(t).fontSize)*Math.hypot(m.a,m.b)};}));for(const t of glyphs){expect(t.font,t.text!).toBeGreaterThanOrEqual(12);expect(t.x,t.text!).toBeGreaterThanOrEqual(0);expect(t.y,t.text!).toBeGreaterThanOrEqual(0);expect(t.right,t.text!).toBeLessThanOrEqual(700);expect(t.bottom,t.text!).toBeLessThanOrEqual(205);}
 const plotGlyphs=await p.locator('.overview-charts svg text,.ab-plot text').evaluateAll(ns=>ns.map(t=>{const svg=t.closest('svg') as SVGSVGElement,b=(t as SVGTextElement).getBBox(),m=(t as SVGTextElement).getScreenCTM()!;return{text:t.textContent,font:parseFloat(getComputedStyle(t).fontSize)*Math.hypot(m.a,m.b),x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,width:svg.viewBox.baseVal.width,height:svg.viewBox.baseVal.height};}));for(const t of plotGlyphs){expect(t.font,t.text!).toBeGreaterThanOrEqual(12);expect(t.x,t.text!).toBeGreaterThanOrEqual(0);expect(t.y,t.text!).toBeGreaterThanOrEqual(0);expect(t.right,t.text!).toBeLessThanOrEqual(t.width);expect(t.bottom,t.text!).toBeLessThanOrEqual(t.height);}
 await p.locator('#chart-bucket').fill('0');await action('[data-event-filter="all"]');await action('#fit-events tbody tr:first-child [data-event-index]');expect(await p.locator('#fit-events').evaluate(n=>getComputedStyle(n).overflowX)).toBe('auto');await action('#fit-add-variant');await expect(p.locator('#fit-active-owner')).toContainText('активный тест');await expect(p.locator('#fit-dock-result-context')).toContainText('вариант A');await action('#fit-f3');const active=JSON.parse(await download('#fit-export-run'));expect(active.durationSeconds).toBe(12);
 await p.locator('#fit-duration').fill('15');await p.locator('#fit-duration').press('Tab');expect(JSON.parse(await download('#fit-export-run'))).toEqual(active);await expect(p.locator('#fit-dock-rate')).not.toHaveText('—');expect(await p.locator('.ab-side-a').innerHTML()).toBe(frozenA);
 await action('#fit-resume');await p.locator('#fit-speed').selectOption('20000');await expect(p.locator('#fit-active-owner')).toContainText('активного теста нет');await action('[data-variant="A"][aria-pressed]');await expect(p.locator('#fit-dock-rate')).toHaveText((await p.locator('.hero-result .metric-focus').textContent())!);
 const result=await download('#fit-export-result');await p.locator('#fit-import').setInputFiles({name:'measured.json',mimeType:'application/json',buffer:Buffer.from(result)});await expect(p.locator('#fit-error')).toHaveText('');expect(await download('#fit-export-result')).toBe(result);expect(await p.locator('.ab-side-a').innerHTML()).toBe(frozenA);await action('#fit-reset');await expect(p.locator('#fit-dock-rate')).toHaveText('—');expect(errors).toEqual([]);await info.attach('worker-responsive',{body:JSON.stringify({width,glyphs,plotGlyphs,checkpoint,errors}),contentType:'application/json'});
 }finally{await c.close().catch(()=>{});}
});
