/** Разрешённая компактная projection пяти строк routed CSV, не каталог кораблей. */
export const ROLE_REFERENCE_SOURCE={revision:"0fe06927ab496918b3547f43412134c100a6e0b4",owner:"docs/data/ship_sensor_ir_em_m_reference_scenarios_v0.1.csv",version:"0.1",units:{temperature:"K",power:"W",range:"m"},scope:"diagnostic_only"} as const;
export const ROLE_REFERENCES=[
  {role:"Civilian",generation:1,id:"civil_warm_coast_350K",status:"reference_diagnostic",temperatureK:350,irReferenceW:507144,emStageBasisW:26000,emReferenceW:.559,irRangeReferenceM:12124,emRangeReferenceM:1113,tactic:"Универсал: сравнить цену оснастки и переключения режима. Тёплый корпус сохраняет IR после выключения генератора."},
  {role:"Industrial",generation:2,id:"industrial_dual_mining_diesel_8min",status:"class_diagnostic",temperatureK:448.48,irReferenceW:9008998,emStageBasisW:56000000,emReferenceW:1204,irRangeReferenceM:51101,emRangeReferenceM:51646,tactic:"Длительная работа: полезная добыча и тепловой баланс важнее краткого скрытого окна. Это candidate rescale, не окончательный M SKU."},
  {role:"Sport",generation:3,id:"sport_pure_electric_packet_4min",status:"class_diagnostic",temperatureK:448.1,irReferenceW:2371941,emStageBasisW:162000000,emReferenceW:3483,irRangeReferenceM:26221,emRangeReferenceM:87842,tactic:"Яркий электрический рывок: EM оплачивает активность. Уход, торможение и восстановление здесь не симулируются."},
  {role:"Military",generation:4,id:"military_combat_10min_no_radar",status:"class_diagnostic",temperatureK:481,irReferenceW:12386015,emStageBasisW:50800000,emReferenceW:1092.2,irRangeReferenceM:59918,emRangeReferenceM:49190,tactic:"Combat diagnostic без intentional RF радара. Цена боя и production конструкция требуют отдельной модели."},
  {role:"Stealth",generation:5,id:"stealth_quiet_350K_sensor_heavy",status:"class_diagnostic",temperatureK:350,irReferenceW:76072,emStageBasisW:1200000,emReferenceW:25.8,irRangeReferenceM:4696,emRangeReferenceM:7560,tactic:"Конечное тихое окно и тепловой долг — критерии развития. Stock G5 RAM не даёт бесплатного EM shielding; активный processing остаётся виден."},
] as const;
