import intake from '../../docs/experiments/parameter-intake.json';
import type {Module,RunSpec,Gate,Origin} from '../model/types';
const gate:Gate={low:150,high:570,restartLow:180,restartHigh:550,workHigh:510};
export function moduleBase(id:string,kind:Module['kind']):Module{return {id,kind,enabled:true,policy:'Active',gate:{...gate},powerW:0,efficiency:1,exportFraction:0,pathEfficiency:1,forceN:0,alpha:0,hostFraction:1,areaM2:0,capacityJ:0,coolingW:0,auxW:0,qJKg:1e7,hotK:800,copEfficiency:.5,workPerJ:0}}
export const presets:RunSpec[]=intake.configurations.map(c=>{
 const g={...moduleBase('generator','generator'),tankId:'diesel',species:'diesel' as const,powerW:c.generator.rated_electrical_w,efficiency:c.generator.eta_gen,exportFraction:c.generator.self_export_fraction,pathEfficiency:c.generator.eta_useful_path};
 const engine={...moduleBase('engine','engine'),tankId:'diesel',species:'diesel' as const,forceN:c.propulsion.march_force_n,alpha:c.propulsion.alpha_kg_per_n_s,efficiency:c.propulsion.useful_fraction,hostFraction:c.propulsion.host_fraction_of_waste,gate:{low:150,high:700,restartLow:180,restartHigh:680,workHigh:570}};
 const laser={...moduleBase('laser','load'),powerW:c.mining_laser.request_bus_w,efficiency:c.mining_laser.beam_efficiency,workPerJ:1/1e8};
 const radiator={...moduleBase('passive','radiator'),areaM2:c.radiator_passive.K_rad_m2};
 const p:RunSpec={schemaVersion:'u2-lab/1',modelVersion:'radiative-host-ledger-0.1',catalogVersion:'intake-0.1',approvedBaseline:false,origins:{},ship:{label:c.label,size:c.identity.size as 'S'|'M',heatCapacityJK:c.thermal.C_ship_j_per_k,dryMassKg:c.mass_ledger.dry_total_kg,hullPowerW:c.hull.background_w,hullRadiationM2:c.hull.K_rad_m2,dischargeEfficiency:.9,chargeEfficiency:1,accumulators:[{id:'accumulator',capacityJ:c.accumulator.stored_capacity_j}],tanks:[{id:'diesel',species:'diesel',capacityKg:c.tank.fuel_capacity_kg,energyJKg:43e6}],modules:[g,engine,laser,radiator],cargoCapacity:c.cargo_hold_universal.capacity_scu},environment:{effectiveBackgroundK:100,solarFluxWm2:0,solarSourceId:'sun',directHeat:[],law:'radiative',linearWK:0},initial:{chargeJ:c.accumulator.stored_capacity_j,temperatureK:300,fuelKg:{diesel:c.tank.initial_fuel_kg},buffersJ:{}},scenario:{name:'Добыча → возвращение → разгрузка',repeat:true,targetWork:12,phases:[{id:'approach',durationSeconds:10,action:'approach',duty:1},{id:'mining',durationSeconds:590,action:'work',duty:1},{id:'return',durationSeconds:10,action:'return',duty:.4},{id:'recovery',durationSeconds:1180,action:'recovery',duty:0},{id:'unload',durationSeconds:10,action:'service',duty:0,service:{refuel:false,unload:true,charge:false}}]},durationSeconds:600,stepSeconds:.1};
 const annotate=(v:unknown,path:string)=>{if(typeof v==='number'){let kind:Origin['kind']='experimental',sourceRef='intake:X6';if(path.includes('capacityJ')){kind='derived';sourceRef='s10 §4; stored e_acc × dry mass'}if(path.includes('cargoCapacity')||path.includes('forceN')||path.includes('hullPowerW')){kind='canonical';sourceRef='s8 §8; s29 cargo'}if(path.includes('heatCapacity'))sourceRef='intake:X3';if(path.includes('alpha')||path.includes('hostFraction'))sourceRef='intake:X2';if(path.includes('efficiency')||path.includes('pathEfficiency'))sourceRef='intake:X1/X7';p.origins[path]={kind,sourceRef,note:'Экспериментальная конфигурация; не утверждённый SKU'};}else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v))annotate(x,path?`${path}.${k}`:k)};
 annotate(p.ship,'ship');annotate(p.initial,'initial');annotate(p.environment,'environment');annotate(p.scenario,'scenario');annotate(p.stepSeconds,'stepSeconds');annotate(p.durationSeconds,'durationSeconds');return p;
});
export function markEdits(p:RunSpec){const walk=(v:any,path:string)=>{if(typeof v==='number')p.origins[path]={kind:'experimental',sourceRef:'user:editable-experiment',note:'Изменённый параметр опыта'};else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v))walk(x,path?`${path}.${k}`:k)};walk(p.ship,'ship');walk(p.initial,'initial');walk(p.environment,'environment');walk(p.scenario,'scenario');walk(p.stepSeconds,'stepSeconds');walk(p.durationSeconds,'durationSeconds')}
