import assert from 'node:assert/strict';
import { createServer } from 'vite';
const server = await createServer({configFile: false, server: {middlewareMode: true, hmr: false}});
const {Retention} = await server.ssrLoadModule('/src/runner/retention.ts');
await server.close();
const channels = Number(process.argv[2]);
global.gc();
const before = process.memoryUsage();
const names = Array.from({length: channels}, (_, i) => 'c' + i);
const r = new Retention(names), values = Object.fromEntries(names.map((n, i) => [n, i]));
for (let i = 1; i <= 50000; i++) r.add(i, values);
global.gc();
const after = process.memoryUsage();
const actualBytes = after.heapUsed - before.heapUsed + after.arrayBuffers - before.arrayBuffers;
console.log(JSON.stringify({channels, actualBytes, ...r.metadata()}));
assert.ok(actualBytes <= 128 * 1048576, 'actual retained heap + array buffers exceed 128 MiB');
assert.ok(r.bytes <= 128 * 1048576);
assert.ok(r.buckets.length <= 50000);
assert.equal(r.totalTicks, 50000);
assert.equal(r.buckets.reduce((n, b) => n + b.count, 0), 50000);
assert.equal(r.buckets.at(-1).endSeconds, 50000);
if (channels === 64) assert.equal(r.buckets.length, 50000);
