import { beforeAll, expect, it } from "vitest";
import { FittingWorkspace } from "../../src/app/fitting-workspace";
import { loadCandidateCatalog, getPresetFit } from "../../src/fitting/catalog";
import { createRun, runChunk, result, type RunResultV2 } from "../../src/runner/run";
import { channelsView } from "../../src/app/fitting-ui/lab-channels";
import { labView } from "../../src/app/fitting-ui/lab-view";
import { compareView } from "../../src/app/fitting-ui/compare-view";
import { shipView } from "../../src/app/fitting-ui/ship-view";
import { channelGroup, channelUnit } from "../../src/app/fitting-ui/telemetry";
import { num } from "../../src/app/fitting-ui/presentation";
const catalog = loadCandidateCatalog();
const workspace = () => new FittingWorkspace(getPresetFit("sputnik:1"), catalog);
const channel = () => ({ group: "energy", unit: "W", hidden: new Set<string>(), eventIndex: 0 });
function complete(w: FittingWorkspace, id: string, seconds = 20, step = 1) {
  w.setConditions({ ...w.getSelected().conditions, durationSeconds: seconds });
  const prepared = w.prepare();
  if (!prepared.ok) throw Error("Invalid fixture");
  const run = createRun(id, { ...prepared.value, stepSeconds: step });
  while (!run.done) runChunk(run, 20000);
  const r = result(run);
  w.showRun(r);
  return r;
}
let long: RunResultV2;
beforeAll(() => { long = complete(workspace(), "long", 4096); });
it("CR-UI-B1 genuine supported 4096-tick trace renders all energy curves and hidden Lab", () => {
  expect(long.status).toBe("complete");
  expect(long.state.timeSeconds).toBe(4096);
  expect(long.buckets).toHaveLength(4096);
  expect(long.channels).toHaveLength(87);
  const ids = long.channels.filter(id => channelGroup(id) === "energy" && channelUnit(id) === "W");
  expect(ids).toHaveLength(21);
  const graph = channelsView(long, channel());
  expect(graph.match(/<polyline /g)).toHaveLength(ids.length);
  expect(graph).toContain("4 096");
  const w = workspace(); w.showRun(long);
  expect(() => labView(w, long, channel(), "all", "")).not.toThrow();
});
it("CR-UI-B1 extrema retain signed finite full-series bounds, selected curves and empty scale", () => {
  const r = structuredClone(long);
  r.buckets = r.buckets.slice(0, 2);
  const ids = r.channels.filter(id => channelGroup(id) === "energy" && channelUnit(id) === "W");
  const i = r.channels.indexOf(ids[0]);
  const c = channel(); ids.slice(1).forEach(id => c.hidden.add(id));
  r.buckets[0].min[i] = -1234567; r.buckets[0].max[i] = Infinity;
  r.buckets[1].min[i] = NaN; r.buckets[1].max[i] = 7654321;
  const graph = channelsView(r, c);
  expect(graph).toContain(num(7654321, "W"));
  const mean = r.buckets[0].sum[i] / r.buckets[0].count;
  expect(graph).toContain(`350,${170 - ((mean + 1234567) / (7654321 + 1234567)) * 150}`);
  c.hidden.add(ids[0]);
  expect(channelsView(r, c)).toContain(num(1, "W"));
  expect(channelsView(r, c)).not.toContain("<polyline ");
  r.buckets = [];
  expect(channelsView(r, channel())).toContain("Видимо 0 buckets");
});
for (const changed of [false, true])
  it(`CR-UI-B2 ${changed ? "changed" : "same"}-fit rerun paused before first chunk keeps history separate`, () => {
    const w = workspace(), old = complete(w, "old");
    expect(w.freeze()).toBe(true);
    const frozen = w.getFrozen();
    w.select("B"); const foreign = complete(w, "foreign"); w.select("A");
    if (changed) { const fit = w.getFit(); fit.initial.chargeFraction = 0.5; w.applyFit(fit); }
    const started = w.start("new"); if (!started.ok) throw Error("start");
    w.setStatus("new", "paused");
    expect(w.getCurrentResult()).toBeUndefined();
    expect(w.getActive()?.spec).toEqual(started.value.spec);
    const view = labView(w, old, channel(), "all", "");
    const context = view.slice(0, view.indexOf('<div class="lab-columns">'));
    const measured = view.slice(view.indexOf('id="fit-result"'), view.indexOf('id="lab-channels"'));
    expect(context).toContain("run new");
    expect(context).not.toContain("run old");
    expect(measured).toContain("Пауза");
    expect(measured).toContain("ожидается первое измерение текущего теста");
    expect(measured).not.toContain("наблюдаемый интервал 0–20");
    expect(compareView(w, "name")).toContain("предыдущий тест · run old");
    expect(shipView(w, 0, new Set())).toContain("Предыдущий тест · run old");
    expect(w.getSelected().result).toEqual(old);
    expect(w.getFrozen()).toEqual(frozen);
    expect(w.acceptResult(old)).toBe(false);
    w.setStatus("old", "running");
    expect(w.getActive()?.status).toBe("paused");
    w.select("B");
    expect(w.getCurrentResult()).toBeUndefined();
    expect(w.getSelected().result).toEqual(foreign);
    const fresh = createRun("new", started.value.spec); runChunk(fresh, 1);
    expect(w.acceptResult(result(fresh))).toBe(true);
    const current = w.getCurrentResult()!;
    expect(current.state.timeSeconds).toBe(started.value.spec.stepSeconds);
    expect(current.spec).toEqual(started.value.spec);
    expect(w.getSelected().result).toEqual(foreign);
    expect(labView(w, current, channel(), "all", "")).toContain("run new");
    w.setStatus("new", "running");
    while (!fresh.done) runChunk(fresh, 20000);
    expect(w.acceptResult(result(fresh))).toBe(true);
    expect(w.getActive()).toBeUndefined();
    expect(w.getCurrentResult()).toEqual(foreign);
    w.select("A"); expect(w.getCurrentResult()?.runId).toBe("new");
    expect(w.getFrozen()).toEqual(frozen);
  });
