// Снимок независимых QA probes; исходный IP12 пропущен, IP18 уточняется отдельным memory probe.
import { createServer } from 'vite';
import assert from 'node:assert/strict';
import { writeFileSync,readFileSync } from 'node:fs';
const server=await createServer({configFile:false,server:{middlewareMode:true,hmr:false}});
const {presets,moduleBase,markEdits}=await server.ssrLoadModule('/src/catalog/presets.ts');
const {stepModel}=await server.ssrLoadModule('/src/model/step.ts');
const {initialState,capacity}=await server.ssrLoadModule('/src/model/types.ts');
const {validateRunSpec}=await server.ssrLoadModule('/src/catalog/schema.ts');
const {createRun,runChunk,result}=await server.ssrLoadModule('/src/runner/run.ts');
const {WorkerController}=await server.ssrLoadModule('/src/runner/protocol.ts');
const {Retention,EventRetention}=await server.ssrLoadModule('/src/runner/retention.ts');
const {compareRuns,freezeRun}=await server.ssrLoadModule('/src/app/compare.ts');
const {serializeRun,parseRunJson,exportTelemetryCsv,exportEventsCsv}=await server.ssrLoadModule('/src/io/json.ts');
await server.close();
const out=[];
const probe=(id,ac,fn)=>{if(id.startsWith('IP12 '))return;try{out.push({id,ac,result:'PASS',evidence:fn()})}catch(e){out.push({id,ac,result:'FAIL',error:String(e),evidence:e.evidence});}};
const near=(a,b,abs=1e-6)=>assert.ok(Math.abs(a-b)<=abs,`${a} expected${b} tolerance${abs}`);
function synthetic(){const p=structuredClone(presets[0]);p.ship.modules=[];p.ship.tanks=[];p.initial.fuelKg={};p.ship.hullPowerW=0;p.ship.hullRadiationM2=0;p.ship.heatCapacityJK=100;p.ship.dryMassKg=1;p.ship.thermalMaterials=[{id:'dry',massKg:1,cpJKgK:100,contents:'dry'}];p.ship.accumulators=[{id:'a',capacityJ:40},{id:'b',capacityJ:60}];p.initial.chargeJ=100;p.ship.chargeEfficiency=1;p.ship.dischargeEfficiency=1;p.environment.effectiveBackgroundK=300;p.scenario.phases=[{id:'work',action:'work',durationSeconds:10,duty:1}];p.scenario.repeat=false;p.durationSeconds=10;p.stepSeconds=.1;markEdits(p);return p;}
function advance(p,duration,dt,requests){let s=initialState(p),energy={};for(let t=0;t<duration-1e-10;t+=dt){const r=stepModel(p.ship,s,p.environment,requests,Math.min(dt,duration-t));s=r.state;for(const[k,v]of Object.entries(r.telemetry))energy[k]=(energy[k]||0)+v*Math.min(dt,duration-t);}return {s,energy};}
probe('IP01 electric analytic protected partial','P3/P4',()=>{const p=synthetic();p.ship.modules=[{...moduleBase('work','load'),powerW:50,efficiency:.5,workPerJ:.01}];p.environment.energyInputs=[{sourceId:'electric',representation:'electric',powerW:20}];const r=stepModel(p.ship,initialState(p),p.environment,[{moduleId:'work',duty:1}],2);near(capacity(p.ship),100);near(r.state.chargeJ,40);near(r.telemetry.deliveredW*2,100);near(r.state.temperatureK,300.5);near(r.telemetry.energyResidualJ,0);const s=initialState(p);s.chargeJ=10;p.environment.energyInputs=[];p.ship.hullPowerW=15;const partial=stepModel(p.ship,s,p.environment,[{moduleId:'work',duty:1}],1);near(partial.state.chargeJ,0);near(partial.telemetry.deliveredW,10);near(partial.telemetry.protectedW,15*10/65);return {chargeJ:r.state.chargeJ,deliveredJ:100,partialDeliveredJ:partial.telemetry.deliveredW,residual:r.telemetry.energyResidualJ};});
probe('IP02 shared H2 generator+engine+cooler permutation','P4/P6',()=>{const p=synthetic();p.ship.heatCapacityJK=1e6;p.ship.tanks=[{id:'h',species:'hydrogen',capacityKg:1,energyJKg:1000},{id:'d',species:'diesel',capacityKg:10,energyJKg:1000}];p.initial.fuelKg={h:1,d:10};p.initial.chargeJ=0;p.ship.hullPowerW=400;p.ship.modules=[{...moduleBase('g','generator'),tankId:'h',species:'hydrogen',powerW:400,efficiency:1},{...moduleBase('e','engine'),tankId:'h',species:'hydrogen',forceN:1,alpha:.4,efficiency:.5,hostFraction:.5},{...moduleBase('h2','h2'),tankId:'h',species:'hydrogen',coolingW:400,qJKg:1000,auxW:0}];const requests=[{moduleId:'e',duty:1}];const a=stepModel(p.ship,initialState(p),p.environment,requests,1);p.ship.modules.reverse();const b=stepModel(p.ship,initialState(p),p.environment,requests,1);near(a.state.fuelKg.h,0);near(a.state.fuelKg.d,10);near(a.telemetry.generatorW,1000/3);near(a.telemetry.h2CoolingW,1000/3);near(a.telemetry.thrustN,5/6);near(a.telemetry.energyResidualJ,0);near(a.state.temperatureK,b.state.temperatureK,1e-10);return {hydrogenRemaining:a.state.fuelKg.h,dieselUnaffected:a.state.fuelKg.d,genW:a.telemetry.generatorW,coolingW:a.telemetry.h2CoolingW,permutationTDelta:a.state.temperatureK-b.state.temperatureK};});
probe('IP03 powered cooling empty/finite','P6',()=>{const p=synthetic();p.ship.modules=[{...moduleBase('h2','h2'),tankId:'h',species:'hydrogen',coolingW:100,qJKg:1000,auxW:10}];p.ship.tanks=[{id:'h',species:'hydrogen',capacityKg:1,energyJKg:1000}];p.initial.fuelKg={h:1};p.initial.chargeJ=0;const r=stepModel(p.ship,initialState(p),p.environment,[],1);near(r.telemetry.h2CoolingW,0);near(r.state.fuelKg.h,1);p.ship.modules=[{...moduleBase('ti','thermoinverter'),coolingW:100,areaM2:100,hotK:800,copEfficiency:.5}];p.initial.chargeJ=100;const t=stepModel(p.ship,initialState(p),p.environment,[],1);near(t.telemetry.tiRejectW,t.telemetry.tiCoolingW+t.telemetry.deliveredW);near(t.telemetry.energyResidualJ,0);p.ship.modules=[{...moduleBase('buf','buffer'),capacityJ:5,coolingW:100}];const b=stepModel(p.ship,initialState(p),p.environment,[],1);near(b.state.buffersJ.buf,5);near(b.telemetry.bufferAbsorbW,5);return {starvedCooling:r.telemetry.h2CoolingW,tiReject:t.telemetry.tiRejectW,bufferAbsorbed:b.telemetry.bufferAbsorbW};});
probe('IP04 Background eligibility starts inside charge dt','P7',()=>{const p=synthetic();p.initial.chargeJ=79;p.environment.energyInputs=[{sourceId:'electric',representation:'electric',powerW:100}];p.ship.modules=[{...moduleBase('bg','load'),policy:'Background',powerW:100,efficiency:1}];const req=[{moduleId:'bg',duty:1}];const coarse=advance(p,.1,.1,req),fine=advance(p,.1,.0001,req);const ev={coarseBackgroundJ:coarse.energy.backgroundW,fineBackgroundJ:fine.energy.backgroundW,coarseCharge:coarse.s.chargeJ,fineCharge:fine.s.chargeJ};if(!(coarse.energy.backgroundW>0&&Math.abs(coarse.energy.backgroundW-fine.energy.backgroundW)<.01)){const e=new Error('within-dt 80% crossing must grant eligible Background; refined independent replay is nonzero');e.evidence=ev;throw e}return ev;});
probe('IP05 Background eligibility starts inside cooling dt','P7',()=>{const p=synthetic();p.initial.temperatureK=500.1;p.ship.hullRadiationM2=1;p.environment.effectiveBackgroundK=100;p.environment.energyInputs=[{sourceId:'electric',representation:'electric',powerW:100}];p.ship.modules=[{...moduleBase('bg','load'),policy:'Background',powerW:100,efficiency:1}];const req=[{moduleId:'bg',duty:1}];const coarse=advance(p,.01,.01,req),fine=advance(p,.01,.00001,req);const ev={coarseBackgroundJ:coarse.energy.backgroundW,fineBackgroundJ:fine.energy.backgroundW,coarseT:coarse.s.temperatureK,fineT:fine.s.temperatureK};if(!(coarse.energy.backgroundW>0)){const e=new Error('Background resumes after crossing 10K hot margin inside dt');e.evidence=ev;throw e}return ev;});
probe('IP06 cancel discards pending step','P10',()=>{const p=synthetic(),out=[];const c=new WorkerController(m=>out.push(m));c.handle({runId:'r',commandId:1,type:'start',payload:{spec:p,maxSteps:1}});c.pump();const before=c.context.state.timeSeconds;c.handle({runId:'r',commandId:2,type:'step'});c.handle({runId:'r',commandId:3,type:'cancel'});c.handle({runId:'r',type:'telemetry-ack',chunkId:1});c.pump();const ev={before,after:c.context.state.timeSeconds,chunks:out.filter(x=>x.type==='chunk').length,acks:out.filter(x=>x.type==='control-ack').map(x=>x.control)};if(c.context.state.timeSeconds!==before){const e=new Error('matching ACK after cancel must not execute queued step');e.evidence=ev;throw e}return ev;});
probe('IP07 schema strict numeric fields missing/strings','P12',()=>{const cases=[['tank.energyJKg numeric string',p=>p.ship.tanks[0].energyJKg='43000000'],['gate.low numeric string',p=>p.ship.modules[0].gate.low='150'],['missing targetWork',p=>delete p.scenario.targetWork],['nonboolean repeat',p=>p.scenario.repeat='false']];const accepted=[];for(const[name,edit]of cases){const p=structuredClone(presets[0]);edit(p);if(validateRunSpec(p).ok)accepted.push(name)}if(accepted.length){const e=new Error('invalid mandatory/types accepted before run');e.evidence={accepted};throw e}return {rejected:cases.map(x=>x[0])};});
probe('IP08 max temperature includes initial state','P13',()=>{const p=synthetic();p.initial.temperatureK=500;p.ship.hullRadiationM2=1;p.durationSeconds=.1;markEdits(p);const r=createRun('peak',p);while(!r.done)runChunk(r,100);const ev={initialT:500,finalT:r.state.temperatureK,maxTemperatureK:r.metrics.maxTemperatureK};if(r.metrics.maxTemperatureK!==500){const e=new Error('cooling-only run peak is initial500K');e.evidence=ev;throw e}return ev;});
probe('IP09 dry-bill/cargo independence radiation sign','P5/P8',()=>{const p=synthetic();p.initial.temperatureK=300;p.ship.hullRadiationM2=1;p.environment.effectiveBackgroundK=400;const r=stepModel(p.ship,initialState(p),p.environment,[],.01);assert.ok(r.telemetry.radiationNetW<0);const q=structuredClone(p);q.ship.cargoCapacity=1e12;q.initial.fuelKg={};const b=stepModel(q.ship,initialState(q),q.environment,[],.01);near(r.state.temperatureK,b.state.temperatureK,1e-12);const dup=structuredClone(presets[0]);dup.ship.thermalMaterials.push(structuredClone(dup.ship.thermalMaterials[0]));assert.equal(validateRunSpec(dup).ok,false);return {netW:r.telemetry.radiationNetW,T:r.state.temperatureK};});
probe('IP10 schema negative/environment doublecount','P8/P12',()=>{const cases=[p=>p.stepSeconds=0,p=>p.durationSeconds=-1,p=>p.initial.temperatureK=-1,p=>p.ship.heatCapacityJK=NaN,p=>p.initial.chargeJ=Infinity,p=>p.ship.modules[1].tankId='foreign',p=>p.initial.fuelKg.diesel=p.ship.tanks[0].capacityKg+1,p=>p.environment.directHeat=[{sourceId:'deep-space',powerW:1}],p=>p.units='Celsius'];for(const edit of cases){const p=structuredClone(presets[0]);edit(p);const v=validateRunSpec(p);assert.equal(v.ok,false);assert.ok(v.errors.every(x=>x.path&&x.message));}return {rejected:cases.length};});
probe('IP11 repeated service chunk replay immutable IO/A-B','P9/P11/P12',()=>{const p=synthetic();p.ship.modules=[{...moduleBase('engine','engine'),tankId:'d',species:'diesel',forceN:1,alpha:.1,efficiency:1}];p.ship.tanks=[{id:'d',species:'diesel',capacityKg:10,energyJKg:1000}];p.initial.fuelKg={d:10};p.durationSeconds=12;p.stepSeconds=.1;p.scenario.repeat=true;p.scenario.phases=[{id:'march',action:'approach',durationSeconds:2,duty:1},{id:'service',action:'service',durationSeconds:1,duty:0,service:{unload:true,charge:false,refuel:true}}];markEdits(p);const a=createRun('a',p),b=createRun('b',p);while(!a.done)runChunk(a,10000);while(!b.done)runChunk(b,7);assert.deepEqual(a.state,b.state);assert.deepEqual(a.metrics,b.metrics);near(a.metrics.fuelConsumedKg.d,.8);assert.deepEqual(parseRunJson(serializeRun(p)).value,JSON.parse(JSON.stringify(p)));const f=freezeRun(result(a));a.spec.ship.cargoCapacity=999;assert.notEqual(f.spec.ship.cargoCapacity,999);const compared=compareRuns(f,result(b),'own-sortie');assert.equal(compared.a.completionSeconds,null);const csv=exportTelemetryCsv(f);assert.ok(csv.includes('physics_dt_s=0.1')&&csv.includes('temperatureK_mean_K'));const mutable=result(b);mutable.events.push({timeSeconds:1,kind:'test',message:'a,"b"\nline'});assert.ok(exportEventsCsv(mutable).includes('"a,""b""\nline"'));return {fuelConsumed:a.metrics.fuelConsumedKg.d,events:a.events.total,exactReplay:true};});
probe('IP12 retained numeric allocation+heap/Event limits','P10',()=>{global.gc();const before=process.memoryUsage();const names=Array.from({length:64},(_,i)=>'c'+i),r=new Retention(names);const values=Object.fromEntries(names.map((n,i)=>[n,i]));for(let i=1;i<=50000;i++)r.add(i,values);global.gc();const after=process.memoryUsage();const numericBytes=r.buckets.reduce((n,b)=>n+b.sum.byteLength+b.min.byteLength+b.max.byteLength,0);const measured=(after.heapUsed-before.heapUsed)+(after.arrayBuffers-before.arrayBuffers);assert.ok(r.buckets.every(b=>b.sum instanceof Float64Array&&b.min instanceof Float64Array&&b.max instanceof Float64Array));assert.equal(numericBytes,50000*64*24);assert.ok(measured<128*1048576);const e=new EventRetention();for(let i=0;i<21001;i++)e.add({timeSeconds:i,kind:'test',message:'event'});assert.equal(e.items().length,20000);assert.equal(e.items()[127].timeSeconds,127);assert.equal(e.items()[128].timeSeconds,1129);assert.equal(e.items().at(-1).timeSeconds,21000);return {buckets:r.buckets.length,channels:64,numericBytes,retentionEstimatedBytes:r.bytes,measuredRetainedHeapPlusArrayBufferDelta:measured,heapDelta:after.heapUsed-before.heapUsed,arrayBufferDelta:after.arrayBuffers-before.arrayBuffers,rssSeparateNotBudget:after.rss,events:e.items().length,dropped:e.dropped};});
probe('IP13 active radiator electrical heat has explicit sink','P4/P6',()=>{const p=synthetic();p.ship.modules=[{...moduleBase('rad','radiator'),areaM2:0,auxW:10}];const r=stepModel(p.ship,initialState(p),p.environment,[],1);const ev={chargeDeltaJ:r.state.chargeJ-p.initial.chargeJ,temperatureDeltaK:r.state.temperatureK-p.initial.temperatureK,deliveredW:r.telemetry.deliveredW,heatInW:r.telemetry.heatInW,heatOutW:r.telemetry.heatOutW,radiationNetW:r.telemetry.radiationNetW,claimedResidualJ:r.telemetry.energyResidualJ,telemetry:r.telemetry};if(r.state.temperatureK===p.initial.temperatureK&&r.telemetry.radiationNetW===0){const e=new Error('10J radiator motor work disappears with zero area; no disclosed heat/work output sink');e.evidence=ev;throw e}return ev;});
probe('IP14 hot+cold restart and active below floors','P7',()=>{const p=synthetic();p.ship.modules=[{...moduleBase('load','load'),powerW:10,gate:{low:100,restartLow:110,workLow:120,workHigh:350,restartHigh:380,high:400}}];let state=initialState(p);const req=[{moduleId:'load',duty:1}],seen=[];for(const t of [100,105,110,400,390,379]){state.temperatureK=t;const r=stepModel(p.ship,state,p.environment,req,.0001);state=r.state;seen.push({T:t,stopped:state.gates.load,deliveredW:r.telemetry.deliveredW});}assert.deepEqual(seen.map(x=>x.stopped),[true,true,false,true,true,false]);p.initial.chargeJ=79;p.ship.modules[0].gate=moduleBase('x','load').gate;const r=stepModel(p.ship,initialState(p),p.environment,req,1);near(r.state.chargeJ,69);p.ship.modules[0].policy='Background';p.initial.chargeJ=100;near(stepModel(p.ship,initialState(p),p.environment,req,1).telemetry.backgroundW,0);return {boundaries:seen,activeChargeBelowFloor:r.state.chargeJ};});
probe('IP15 PV ledger + nonlinear half-step','P5/P8',()=>{const p=synthetic();p.initial.chargeJ=0;p.environment.solarFluxWm2=20;p.ship.modules=[{...moduleBase('pv','solar'),areaM2:2,efficiency:.25}];const r=stepModel(p.ship,initialState(p),p.environment,[],1);near(r.telemetry.solarW,10);near(r.telemetry.solarHostW,30);near(r.state.chargeJ,10);near(r.state.temperatureK,300.3);near(r.telemetry.energyResidualJ,0);p.ship.modules=[];p.environment.solarFluxWm2=0;p.ship.heatCapacityJK=1e5;p.ship.hullRadiationM2=100;p.initial.temperatureK=500;p.environment.effectiveBackgroundK=100;const a=advance(p,5,.05,[]),b=advance(p,5,.025,[]);const relativeT=Math.abs(a.s.temperatureK-b.s.temperatureK)/b.s.temperatureK,relativeEnergy=Math.abs(a.energy.radiationNetW-b.energy.radiationNetW)/b.energy.radiationNetW;assert.ok(relativeT<.001&&relativeEnergy<.001);return {absorbedW:40,electricW:10,heatW:30,halfStepRelativeT:relativeT,halfStepRelativeEnergy:relativeEnergy};});
probe('IP16 real eight-hour persistent replay + completed A/B checkpoints','P9/P11',()=>{const p=structuredClone(presets[0]);p.durationSeconds=28800;p.stepSeconds=1;markEdits(p);const run=createRun('8h',p);while(!run.done)runChunk(run,100000);assert.equal(run.state.timeSeconds,28800);assert.ok(run.metrics.usefulWork>12&&run.metrics.fuelConsumedKg.diesel>0&&run.state.fuelKg.diesel<p.initial.fuelKg.diesel);const a=result(run);const same=compareRuns(a,a,'same-task'),own=compareRuns(a,a,'own-sortie');near(same.a.usefulWork,12);assert.ok(same.a.completionSeconds<own.a.completionSeconds);assert.ok(same.a.fuelConsumedKg.diesel<own.a.fuelConsumedKg.diesel);return {duration:28800,dt:1,ticks:run.metrics.ticks,work:run.metrics.usefulWork,fuel:run.metrics.fuelConsumedKg.diesel,targetTime:same.a.completionSeconds,sortieTime:own.a.completionSeconds};});
probe('IP17 shipped S/M catalog JSON runnable/provenance','P2/P12',()=>{const ev=[];for(const [i,size]of ['s','m'].entries()){const json=JSON.parse(readFileSync(`data/catalog/${size}-civilian.json`,'utf8'));assert.equal(validateRunSpec(json).ok,true);assert.deepEqual(json,JSON.parse(JSON.stringify(presets[i])));assert.equal(json.approvedBaseline,false);ev.push({size:json.ship.size,model:json.modelVersion,alpha:json.ship.modules[1].alpha,alphaOrigin:json.origins['ship.modules.1.alpha'].kind,thrustN:json.ship.modules[1].forceN});}assert.notEqual(ev[1].thrustN,ev[0].thrustN*4);return ev;});
probe('IP18 retained storage cap with admitted larger channel count','P10',()=>{const p=structuredClone(presets[0]);p.ship.modules=[];p.ship.hullPowerW=0;p.ship.hullRadiationM2=0;p.durationSeconds=50000;p.stepSeconds=1;for(let i=0;i<56;i++){p.ship.tanks.push({id:'extra'+i,species:'diesel',capacityKg:1,energyJKg:1000});p.initial.fuelKg['extra'+i]=1;}markEdits(p);assert.equal(validateRunSpec(p).ok,true);const admitted=createRun('channel-boundary',p);runChunk(admitted,1);assert.equal(admitted.retention.channels.length,96);global.gc();const before=process.memoryUsage(),names=admitted.retention.channels,r=new Retention(names),values=Object.fromEntries(names.map((n,i)=>[n,i]));for(let i=1;i<=50000;i++)r.add(i,values);global.gc();const after=process.memoryUsage();const actual=(after.heapUsed-before.heapUsed)+(after.arrayBuffers-before.arrayBuffers);const ev={channels:96,buckets:r.buckets.length,maxBuckets:r.maxBuckets,estimatedBytes:r.bytes,actualRetainedHeapPlusArrayBufferDelta:actual,limitBytes:128*1048576,numericBytes:r.buckets.reduce((n,b)=>n+b.sum.byteLength+b.min.byteLength+b.max.byteLength,0)};if(actual>128*1048576){const e=new Error('≤128MiB retained budget exceeded while declared estimate remains below limit; no schema channel cap and duration has no12h cap');e.evidence=ev;throw e}return ev;});
writeFileSync(new URL('./probes.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
