import type {CandidateCatalog,ShipFit,FitValidation,Slot} from '../fitting/types';
import {getPresetFit} from '../fitting/catalog';
import {validateFit} from '../fitting/validate';
import {compileFit} from '../fitting/compile';
import {FittingSession} from './fitting-session';
import {compareMiningConditions,type MiningConditions} from '../scenarios/fitting';
import type {RunSpecV2} from '../model/v2/types';
import type {RunResultV2} from '../runner/run';
import {drawChart,format} from './charts';
import type {Bucket} from '../runner/retention';
import type {MiningMetrics} from '../runner/mining-metrics';
export type FittingController={getFit():ShipFit;applyFit(f:ShipFit):FitValidation;showRun(r:RunResultV2):void;destroy():void};
const escaped=(x:unknown)=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const newId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const causes:Record<string,string>={power:'Питание',thermal:'Тепло',resource:'Ресурс',cargo:'Трюм'};
const categories:Record<string,string>={propulsion:'Двигатели',power:'Питание',payload:'Полезная нагрузка',signature:'Контроль сигнатур'};
const roles:Record<string,string>={march:'Марш',retro:'Торможение',strafe:'Стрейф — пара',turn:'Поворот — пара'};
export function mountFitting(root:HTMLElement,catalog:CandidateCatalog,onRun:(s:RunSpecV2)=>void):FittingController {
 const session=new FittingSession(getPresetFit('sputnik'),catalog);
 const worker=new Worker(new URL('../runner/worker.ts',import.meta.url),{type:'module'});
 let selectedSlot='payload-1',candidate='',runId=newId(),commandId=0,active=false,current:RunResultV2|undefined,activeSpec:RunSpecV2|undefined;
 let channels:string[]=[],buckets:Bucket[]=[],lastMetrics:MiningMetrics|undefined;
 const pending=new Map<number,number>();
 root.innerHTML=`<header><div class="title"><span class="wordmark">U2</span><div><h1>U2 Ship Fitting</h1><div class="subtitle">Оснастка и добывающая работа · лаборатория</div></div></div><span class="badge">ЭКСПЕРИМЕНТАЛЬНЫЕ ТТХ</span></header>
 <nav class="fit-nav"><a href="#fit-layout">Оснастка</a><a href="#fit-experiment">Power & Heat</a><a href="#fit-comparison">Сравнение</a><a href="?mode=legacy">Legacy v1</a><button id="fit-save">Сохранить сборку</button><label class="file-button">Импорт<input id="fit-import" type="file" accept=".json"></label></nav>
 <div class="fit-f1"><strong id="fit-readiness"></strong><span id="fit-status">Опыт ещё не запускался</span><span id="fit-first">Первое ограничение: не выявлено за опыт</span><strong id="fit-rate">— SCU/h</strong></div><div id="fit-error" class="error" role="alert"></div>
 <div id="fit-layout" class="fit-layout"><aside class="fit-panel"><h2>Корпус и задача</h2><label for="fit-preset">Готовая конфигурация</label><select id="fit-preset"></select><div id="fit-summary"></div><div class="field"><label for="fit-charge-fraction">Исходный заряд · доля [0…1]</label><input id="fit-charge-fraction" type="number" min="0" max="1" step=".1" value="1"></div><div class="field"><label for="fit-fuel-fraction">Исходная соларка · доля [0…1]</label><input id="fit-fuel-fraction" type="number" min="0" max="1" step=".1" value="1"></div><div class="field"><label for="fit-h2-fraction">Исходный H₂ · доля [0…1]</label><input id="fit-h2-fraction" type="number" min="0" max="1" step=".1" value="1"></div><p class="model-note">SCU = м³. Плотность товара определяет массу. Запас топлива не является грузовым трюмом.</p></aside>
 <section class="fit-panel"><h2>Оснастка</h2><h3>Встроенные системы</h3><div id="fit-builtins"></div><h3>Сменные слоты</h3><div id="fit-slots"></div></section>
 <aside class="fit-panel"><h2>Каталог и замена</h2><label for="fit-slot">Выбранный слот</label><select id="fit-slot"></select><label><input id="fit-all-items" type="checkbox"> Показать несовместимые</label><label for="fit-item">Изделие</label><select id="fit-item"></select><div id="fit-preview"></div><button id="fit-apply" class="primary">Применить замену</button><button id="fit-remove">Снять изделие</button><p class="model-note">Номинальные параметры зависят от условий. Реальный результат появится после опыта.</p></aside></div>
 <section id="fit-experiment" class="fit-panel"><h2>Power & Heat · опыт добычи</h2><div class="fit-conditions"><div class="field"><label for="fit-duration">Горизонт · s</label><input id="fit-duration" type="number" value="600" min=".01"></div><div class="field"><label for="fit-background">Фон · K</label><input id="fit-background" type="number" value="100" min="0"></div><div class="field"><label for="fit-work-seconds">Рабочая фаза · s</label><input id="fit-work-seconds" type="number" value="120" min=".01"></div><div class="field"><label for="fit-duty">Рабочая доля [0…1]</label><input id="fit-duty" type="number" value="1" min="0" max="1" step=".1"></div><div class="field"><label for="fit-density">Плотность руды · kg/m³</label><input id="fit-density" type="number" value="1500" min="1"></div><div class="field"><label for="fit-return">Возврат тепла · доля</label><input id="fit-return" type="number" value=".35" min="0" max="1" step=".01"></div><div class="field"><label for="fit-target">Цель добычи · SCU</label><input id="fit-target" type="number" value="1000" min="0"></div></div>
 <div class="toolbar fit-controls"><button id="fit-start" class="primary">Запустить</button><button id="fit-pause">Пауза</button><button id="fit-resume">Продолжить</button><button id="fit-step">Шаг</button><button id="fit-reset">Сброс</button><button id="fit-cancel">Отмена</button><label>Расчёт × <select id="fit-speed"><option>1</option><option>100</option><option selected>2000</option><option>20000</option></select></label><span id="fit-ack"></span></div>
 <p><span id="fit-running-revision">Опыт не запущен</span> · <span id="fit-next-revision">Следующая сборка: 1</span> · <strong id="fit-time">0 s</strong></p><div id="fit-result">Измерения появятся после запуска.</div><div class="fit-charts"><canvas id="fit-power-chart" aria-label="Запрос и фактическое питание"></canvas><canvas id="fit-thermal-chart" aria-label="Температура корабля"></canvas></div><p id="fit-retention" class="model-note">Каналы фиксируются при запуске. График: mean/min/max/count.</p><details><summary>Журнал событий</summary><div id="fit-events"></div></details></section>
 <section class="fit-panel"><h2>Сравнение A/B</h2><button id="fit-freeze">Зафиксировать A</button><div id="fit-comparison">Запустите опыт, зафиксируйте A и измените сборку для B.</div></section>
 <details class="fit-panel"><summary id="fit-f3">Подробнее · SI, источники, ledger и экспорт</summary><p class="model-note">Числа U2, расчёты и гипотезы различаются по происхождению. Эксперимент не является production proof.</p><pre id="fit-sources"></pre><label for="fit-variant-power">Собственный вариант: номинальная мощность · W</label><input id="fit-variant-power" type="number" min="0"><button id="fit-variant">Создать вариант выбранного изделия</button><button id="fit-export-run">Экспорт опыта JSON</button><button id="fit-export-result">Экспорт результата JSON</button><button id="fit-export-csv">Экспорт измерений CSV</button><pre id="fit-ledger"></pre></details><footer>U2 Lab · <span id="fit-version">0.1.1 · candidate Ship Fitting</span> · физическое второе устройство проверяется отдельно</footer>`;
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>root.querySelector('#'+id) as T;
 const text=(id:string,value:unknown)=>el(id).textContent=String(value);
 const error=(value:string)=>text('fit-error',value);
 const conditions=():MiningConditions=>({durationSeconds:el<HTMLInputElement>('fit-duration').valueAsNumber,effectiveBackgroundK:el<HTMLInputElement>('fit-background').valueAsNumber,workSeconds:el<HTMLInputElement>('fit-work-seconds').valueAsNumber,duty:el<HTMLInputElement>('fit-duty').valueAsNumber,densityKgM3:el<HTMLInputElement>('fit-density').valueAsNumber,returnFraction:el<HTMLInputElement>('fit-return').valueAsNumber,targetM3:el<HTMLInputElement>('fit-target').valueAsNumber});
 const presetOptions=catalog.hulls.flatMap(h=>{const max=h.slots.filter(s=>s.category==='payload').length+(h.id==='pony'?1:0);return Array.from({length:Math.min(3,max)},(_,i)=>`<option value="${h.id}:${i+1}">${escaped(h.label)} · ${i+1} лазер${i?'а':''}</option>`);});
 el('fit-preset').innerHTML=presetOptions.join('');
 const edited=(slot:Slot,itemId:string):ShipFit=>{const f=session.getFit();let id=f.assignments[slot.id]??'fit:'+slot.id;f.assignments[slot.id]=id;f.instances[id]={id,itemId,enabled:f.instances[id]?.enabled??true};return f;};
 function preview(){const f=session.getFit(),h=catalog.hulls.find(h=>h.id===f.hullId)!;const slot=h.slots.find(s=>s.id===selectedSlot)!;candidate=el<HTMLSelectElement>('fit-item').value;const item=catalog.items[candidate]??f.localVariants[candidate];el<HTMLButtonElement>('fit-apply').disabled=!item;el<HTMLButtonElement>('fit-remove').disabled=!f.assignments[slot.id];if(!item){text('fit-preview','Нет изделий для выбранного слота');return;}
  const next=edited(slot,candidate),v=validateFit(next,catalog);const beforeId=f.instances[f.assignments[slot.id]]?.itemId;const before=f.localVariants[beforeId]??catalog.items[beforeId];const mass=(m:typeof item|undefined)=>m?.materials.reduce((n,b)=>n+b.massKg,0)??0;const C=(m:typeof item|undefined)=>m?.materials.reduce((n,b)=>n+b.massKg*b.cpJKgK,0)??0;
  const rows=[['Изделие',before?.label??'Пусто',item.label],['Масса · kg',mass(before),mass(item)],['C · J/(kg·K)',C(before),C(item)],['Номинальная мощность · W',before?.numerics.powerW??0,item.numerics.powerW??0],['Cargo · SCU',before?.numerics.cargoM3??0,item.numerics.cargoM3??0],['Радиатор · m²',before?.numerics.areaM2??0,item.numerics.areaM2??0]];
  el('fit-preview').innerHTML='<h3>Номинальные параметры</h3><table><thead><tr><th>Параметр</th><th>Сейчас</th><th>После замены</th></tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+escaped(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table><p>Дельта массы: '+escaped(mass(item)-mass(before))+' kg</p>'+(v.valid?'':`<p class="error">${v.issues.filter(i=>i.severity==='error').map(i=>escaped(i.message)).join(' · ')}</p>`);
  el<HTMLButtonElement>('fit-apply').disabled=!v.valid;text('fit-sources',JSON.stringify({selectedItem:item,fitVersion:f.schemaVersion,catalogVersion:f.catalogVersion,model:activeSpec?.modelVersion,units:'SI'},null,2));el<HTMLInputElement>('fit-variant-power').value=String(item.numerics.powerW??0);
 }
 function catalogView(){const f=session.getFit(),h=catalog.hulls.find(h=>h.id===f.hullId)!,slot=h.slots.find(s=>s.id===selectedSlot)!;const all=el<HTMLInputElement>('fit-all-items').checked;const items=Object.values({...catalog.items,...f.localVariants}).filter(m=>all||validateFit(edited(slot,m.id),catalog).valid);el('fit-item').innerHTML=items.map(m=>`<option value="${escaped(m.id)}">${escaped(m.label)} · ${m.size}</option>`).join('');const current=f.instances[f.assignments[slot.id]]?.itemId;if(items.some(m=>m.id===current))el<HTMLSelectElement>('fit-item').value=current;preview();}
 function render(){const f=session.getFit(),h=catalog.hulls.find(h=>h.id===f.hullId)!,v=validateFit(f,catalog);const compiled=compileFit(f,catalog);text('fit-readiness',v.readiness.canRun?'Монтаж совместим · комплектность: готова'+(v.readiness.resourceWarnings.length?' · '+v.readiness.resourceWarnings.map(i=>i.message).join(' · '):''):'Комплектность: не хватает '+v.readiness.missing.join(', '));el<HTMLButtonElement>('fit-start').disabled=!v.readiness.canRun;el('fit-summary').innerHTML=`<p>${escaped(h.size)} · ${escaped(h.class)} · архитектура ${h.architecture}</p><p>Задача: добыча LAB-ORE-01</p>`+(compiled.ok?`<p>Сухая масса: ${compiled.value.dryMassKg.toFixed(1)} kg<br>C: ${format(compiled.value.heatCapacityJK)} J/K<br>Груз: ${compiled.value.cargoCapacityM3.universal} универсальных + ${compiled.value.cargoCapacityM3.bulk} навалочных SCU</p>`:'<p>Сухой bill появится после комплектования.</p>');
  el('fit-builtins').innerHTML=h.builtins.map(b=>`<p>${escaped(b.item.label)} · ${escaped(b.item.materials.reduce((n,m)=>n+m.massKg,0).toFixed(1))} kg<br>🔒 Встроено: заменить нельзя${b.item.family==='mining'?` <label><input type="checkbox" data-builtin-enable="${escaped(b.id)}" ${f.builtinModes?.[b.id]?.enabled===false?"":"checked"}> Включён в неизменной рабочей группе</label>`:''}</p>`).join('');
  for(const checkbox of root.querySelectorAll<HTMLInputElement>('[data-builtin-enable]'))checkbox.onchange=()=>{const next=session.getFit();next.builtinModes={...next.builtinModes,[checkbox.dataset.builtinEnable!]:{enabled:checkbox.checked}};apply(next);};
  el('fit-slots').innerHTML=Object.entries(categories).map(([cat,label])=>`<details open><summary>${label} · ${h.slots.filter(s=>s.category===cat&&f.assignments[s.id]).length}/${h.slots.filter(s=>s.category===cat).length}</summary>${cat==='signature'?'<p class="model-note">Тепловое оборудование; обнаружение пока не рассчитывается.</p>':''}${h.slots.filter(s=>s.category===cat).map(s=>{const i=f.instances[f.assignments[s.id]],m=i&&(f.localVariants[i.itemId]??catalog.items[i.itemId]);return `<div class="fit-slot-card"><button data-fit-slot="${s.id}">${escaped(roles[s.role??'']??s.id)} · ${s.size}<br>${escaped(m?.label??(s.mandatory?'Пустой обязательный слот':'Пусто'))}</button>${i?`<label><input type="checkbox" data-fit-enable="${escaped(i.id)}" ${i.enabled?'checked':''}> Включён · ${escaped(i.id)}</label>`:''}</div>`;}).join('')}</details>`).join('');
  el('fit-slot').innerHTML=h.slots.map(s=>`<option value="${s.id}">${escaped(roles[s.role??'']??s.id)} · ${s.size}</option>`).join('');if(!h.slots.some(s=>s.id===selectedSlot))selectedSlot='payload-1';el<HTMLSelectElement>('fit-slot').value=selectedSlot;
  for(const button of root.querySelectorAll<HTMLButtonElement>('[data-fit-slot]'))button.onclick=()=>{selectedSlot=button.dataset.fitSlot!;el<HTMLSelectElement>('fit-slot').value=selectedSlot;catalogView();el('fit-item').focus();};
  for(const checkbox of root.querySelectorAll<HTMLInputElement>('[data-fit-enable]'))checkbox.onchange=()=>{const next=session.getFit();next.instances[checkbox.dataset.fitEnable!].enabled=checkbox.checked;apply(next);};
  text('fit-next-revision','Следующая сборка: '+f.fitRevision);for(const [id,val]of [['fit-charge-fraction',f.initial.chargeFraction],['fit-fuel-fraction',f.initial.fuelFraction.diesel??1],['fit-h2-fraction',f.initial.fuelFraction.hydrogen??1]] as const)el<HTMLInputElement>(id).value=String(val);catalogView();
 }
 function apply(f:ShipFit):FitValidation{const v=session.applyFit(f);if(v.valid){error('');render();}else error(v.issues.filter(i=>i.severity==='error').map(i=>i.message).join('\n'));return v;}
 function send(type:string,payload?:unknown){const id=++commandId;pending.set(id,performance.now());worker.postMessage({runId,commandId:id,type,payload});}
 function reset(){if(active)send('cancel');runId=newId();pending.clear();active=false;activeSpec=undefined;current=undefined;lastMetrics=undefined;buckets=[];channels=[];text('fit-time','0 s');text('fit-running-revision','Опыт не запущен');text('fit-status','Опыт ещё не запускался');text('fit-result','Измерения появятся после запуска.');text('fit-first','Первое ограничение: не выявлено за опыт');text('fit-rate','— SCU/h');draw();}
 function start(){const v=session.prepareRun(conditions());if(!v.ok){error(v.errors.map(e=>e.path+': '+e.message).join('\n'));return;}reset();activeSpec=structuredClone(v.value);active=true;onRun(structuredClone(v.value));text('fit-running-revision','Опыт использует сборку: '+v.value.resolvedShip.fit.fitRevision);text('fit-status','Выполняется');error('');send('start',{spec:v.value,maxSteps:Number(el<HTMLSelectElement>('fit-speed').value)});}
 function draw(){drawChart(el<HTMLCanvasElement>('fit-power-chart'),buckets,channels,[{channel:'requestedW',color:'#e0b57c',label:'Запрос'},{channel:'deliveredW',color:'#91d8b9',label:'Факт'}],'W');drawChart(el<HTMLCanvasElement>('fit-thermal-chart'),buckets,channels,[{channel:'temperatureK',color:'#ecb185',label:'Температура'}],'K');}
 const number=(n:number|null|undefined,unit='')=>n==null?'не определено':n.toFixed(4)+(unit?' '+unit:'');
 function measured(m:MiningMetrics,state:RunResultV2['state']){lastMetrics=m;text('fit-time',number(state.timeSeconds,'s'));const first=m.firstLimiter?m.firstLimiter.causes.map(c=>causes[c]).join(' + ')+' · '+number(m.firstLimiter.timeSeconds,'s'):'не выявлено за опыт';text('fit-first','Первое ограничение: '+first);text('fit-rate',number(m.scuPerHour,'SCU/h'));el('fit-result').innerHTML=`<p>${m.firstTargetSeconds!==null?'Задача выполнена'+(m.firstLimiter?' с ограничениями':''):'Задача не завершена в горизонте'}</p><div class="fit-measured">${[['Добыча',number(m.usefulWork,'SCU')],['Производительность',number(m.scuPerHour,'SCU/h')],['Использование добывающей оснастки',number(m.kUseHorizon==null?null:m.kUseHorizon*100,'%')],['Интервал K_use',m.intervalLabel],['Добыча завершённых циклов',number(m.completedCycles.scu,'SCU')],['Полные циклы',m.cyclesCompleted],['Соларка',number(m.fuelPerScu.diesel,'kg/SCU')],['H₂ общий',number(m.fuelPerScu.hydrogen,'kg/SCU')],['H₂ охладитель (часть общего)',number(m.h2CoolerKg,'kg')],['Вынужденный простой',number(m.forcedDowntimeSeconds,'s')],['Частичная потеря добычи',number(m.partialLossM3,'SCU')],['Первое восстановление',m.recovery.firstSeconds===null?'не восстановился за время опыта':number(m.recovery.firstSeconds,'s')],['Восстановления count / mean / max',m.recovery.count+' / '+number(m.recovery.meanSeconds,'s')+' / '+number(m.recovery.maxSeconds,'s')],['Перекрытие причин',number(m.overlapSeconds,'s')],['Текущая масса',number(state.currentMassKg,'kg')],['Пик температуры',number(m.maxTemperatureK,'K')]].map(([label,value])=>`<div><span>${escaped(label)}</span><strong>${escaped(value)}</strong></div>`).join('')}</div><p class="model-note">K_use фиксированной выбранной группы включает перелёт, обслуживание и ручное выключение; рядом показана абсолютная добыча/h. Длительности причин перекрываются: ${Object.entries(m.causeSeconds).map(([c,n])=>escaped(causes[c])+': '+number(n,'s')).join(' · ')}.</p>${m.propulsionShortfall?'<p class="notice warning">Тяга недоставлена. Заданные времена фаз не доказывают завершение маршрута.</p>':''}`;text('fit-ledger',JSON.stringify({energyResidualJ:m.energyResidualJ,sourceEnergyJ:m.sourceEnergyJ,beamEnergyJ:m.beamEnergyJ,returnHeatJ:m.returnHeatJ,fuelPurposeKg:m.fuelPurposeKg},null,2));}
 function compare(){const a=session.a;if(!a)return;if(!current){text('fit-comparison','A сохранён · '+number(a.metrics.usefulWork,'SCU')+' · сборка '+a.spec.resolvedShip.fit.fitRevision);return;}const c=compareMiningConditions(a.spec,current.spec);el('fit-comparison').innerHTML=`<p>${c.comparable?'Одинаковые условия · контролируемое сравнение':'Условия отличаются: '+escaped(c.differences.join(', '))}</p><div class="fit-table-scroll"><table><thead><tr><th>Показатель</th><th>A</th><th>B</th></tr></thead><tbody>${[['Добыча SCU',a.metrics.usefulWork,current.metrics.usefulWork],['SCU/h',a.metrics.scuPerHour,current.metrics.scuPerHour],['K_use',a.metrics.kUseHorizon,current.metrics.kUseHorizon],['Соларка kg/SCU',a.metrics.fuelPerScu.diesel,current.metrics.fuelPerScu.diesel],['H₂ kg/SCU',a.metrics.fuelPerScu.hydrogen,current.metrics.fuelPerScu.hydrogen],['Простой s',a.metrics.forcedDowntimeSeconds,current.metrics.forcedDowntimeSeconds]].map(row=>'<tr>'+row.map(x=>'<td>'+escaped(x??'не определено')+'</td>').join('')+'</tr>').join('')}</tbody></table></div>`;}
 function showRun(r:RunResultV2){current=structuredClone(r);measured(r.metrics,r.state);buckets=r.buckets;channels=r.channels;draw();compare();}
 worker.onmessage=event=>{const m=event.data;if(m.runId!==runId)return;if(m.type==='control-ack'){const started=pending.get(m.commandId);if(started!==undefined){text('fit-ack',m.control+' ACK · '+(performance.now()-started).toFixed(1)+' ms');pending.delete(m.commandId);}const labels:Record<string,string>={pause:'Пауза',step:'Шаг',resume:'Выполняется',cancel:'Отменён'};if(labels[m.control])text('fit-status',labels[m.control]);}if(m.type==='error'){error(m.payload);text('fit-status','Ошибка');}if(m.type==='chunk'){const p=m.payload;buckets=p.buckets;channels=p.channels;measured(p.metrics,p.state);text('fit-retention',`${p.channels.length} каналов · ${p.retention.buckets}/${p.retention.maxBuckets} buckets · ${p.retention.cadenceSeconds}s mean/min/max/count · ${(p.retention.estimatedBytes/1048576).toFixed(2)} MiB · events ${p.retention.totalEvents}, отброшено ${p.retention.droppedEvents}`);el('fit-events').innerHTML=p.events.map((e:any)=>`<p>${escaped(e.timeSeconds)} s · ${escaped(e.kind)} · ${escaped(e.message)}</p>`).join('');draw();worker.postMessage({runId,type:'telemetry-ack',chunkId:m.chunkId});}if(m.type==='complete'||m.type==='snapshot'){showRun(m.payload);if(m.type==='complete'){active=false;text('fit-status','Завершён');}}};
 el<HTMLSelectElement>('fit-preset').onchange=e=>{const f=getPresetFit((e.target as HTMLSelectElement).value);apply(f);};el<HTMLSelectElement>('fit-slot').onchange=e=>{selectedSlot=(e.target as HTMLSelectElement).value;catalogView();};el<HTMLInputElement>('fit-all-items').onchange=catalogView;el<HTMLSelectElement>('fit-item').onchange=preview;
 el('fit-apply').onclick=()=>{const f=session.getFit(),h=catalog.hulls.find(h=>h.id===f.hullId)!;apply(edited(h.slots.find(s=>s.id===selectedSlot)!,candidate));};el('fit-remove').onclick=()=>{const f=session.getFit();delete f.instances[f.assignments[selectedSlot]];delete f.assignments[selectedSlot];apply(f);};
 for(const [id,species]of [['fit-fuel-fraction','diesel'],['fit-h2-fraction','hydrogen'],['fit-charge-fraction','charge']] as const)el<HTMLInputElement>(id).onchange=()=>{const f=session.getFit(),n=el<HTMLInputElement>(id).valueAsNumber;if(species==='charge')f.initial.chargeFraction=n;else f.initial.fuelFraction[species]=n;apply(f);};
 el('fit-start').onclick=start;el('fit-reset').onclick=reset;for(const control of ['pause','resume','step','cancel'])el('fit-'+control).onclick=()=>{if(control==='step'&&!activeSpec){start();send('pause');}send(control);};
 el('fit-freeze').onclick=()=>{if(current){session.freeze(current);current=undefined;compare();}else error('Сначала завершите опыт или нажмите Отмена для снимка.');};
 const download=(name:string,value:string,type='application/json')=>{const url=URL.createObjectURL(new Blob([value],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 el('fit-save').onclick=()=>download('u2-ship-fit.json',JSON.stringify(session.getFit(),null,2));el('fit-export-run').onclick=()=>{const v=session.prepareRun(conditions());if(v.ok)download('u2-fitting-experiment.json',JSON.stringify(v.value,null,2));else error(v.errors.map(e=>e.message).join('\n'));};el('fit-export-result').onclick=()=>current?download('u2-fitting-result.json',JSON.stringify(current,(_,v)=>ArrayBuffer.isView(v)?Array.from(v as any):v,2)):error('Сначала завершите опыт.');
 el<HTMLInputElement>('fit-import').onchange=async e=>{const input=e.target as HTMLInputElement;const file=input.files?.[0];if(file)try{const f=JSON.parse(await file.text());const v=apply(f);if(v.valid)reset();}catch(e){error('$: Ошибка JSON: '+String(e));}input.value='';};
 el('fit-variant').onclick=()=>{const f=session.getFit(),base=f.localVariants[candidate]??catalog.items[candidate],power=el<HTMLInputElement>('fit-variant-power').valueAsNumber;if(!base||!Number.isFinite(power)||power<0){error('Нужна конечная мощность ≥0 W');return;}const item=structuredClone(base),id='local:'+newId();item.id=id;item.label=base.label+' · собственный вариант';item.numerics.powerW=power;item.origins['numerics.powerW']={kind:'experimental',sourceRef:'lab:user-variant',unit:'W',note:'Собственный численный вариант'};f.localVariants[id]=item;f.instances[f.assignments[selectedSlot]].itemId=id;apply(f);};
 const resize=()=>draw();window.addEventListener('resize',resize);render();draw();return {getFit:()=>session.getFit(),applyFit:apply,showRun,destroy(){worker.terminate();window.removeEventListener('resize',resize);root.replaceChildren();}};
}
