import {it,expect} from 'vitest';
import {presets,moduleBase,markEdits} from '../../src/catalog/presets';
import {initialState} from '../../src/model/types';
import {stepModel,SIGMA} from '../../src/model/step';
function fixture(){const p=structuredClone(presets[0]);p.ship.modules=[];p.ship.hullPowerW=0;p.ship.hullRadiationM2=0;p.ship.heatCapacityJK=1000;p.ship.accumulators=[{id:'a',capacityJ:1000}];p.initial.chargeJ=1000;p.ship.dischargeEfficiency=1;return p}
it('bounds partial battery depletion and records energy/heat from actual delivery',()=>{const p=fixture();p.ship.modules=[{...moduleBase('laser','load'),powerW:100,efficiency:.5,workPerJ:.01}];const s=initialState(p);s.chargeJ=50;const r=stepModel(p.ship,s,p.environment,[{moduleId:'laser',duty:1}],1);expect(r.state.chargeJ).toBeCloseTo(0,9);expect(r.telemetry.deliveredW).toBeCloseTo(50);expect(r.state.usefulWork).toBeCloseTo(.25);expect(r.state.temperatureK).toBeCloseTo(300.025);expect(r.telemetry.energyResidualJ).toBeCloseTo(0,6)});
it('chemical thrust works with empty electric stock and does not cool existing heat',()=>{const p=fixture();p.ship.heatCapacityJK=1e9;p.ship.modules=[{...moduleBase('engine','engine'),tankId:'diesel',species:'diesel',forceN:1e6,alpha:5.65e-7,efficiency:.32,hostFraction:.05}];const s=initialState(p);s.chargeJ=0;const r=stepModel(p.ship,s,p.environment,[{moduleId:'engine',duty:1}],1);expect(r.state.fuelKg.diesel).toBeCloseTo(6000-.565);expect(r.telemetry.thrustN).toBeCloseTo(1e6);expect(r.state.temperatureK).toBeGreaterThan(300);expect(r.telemetry.energyResidualJ).toBeCloseTo(0,6)});
it('joint shared H2 flow is permutation invariant after midstep depletion',()=>{const p=fixture();p.ship.tanks=[{id:'h',species:'hydrogen',capacityKg:1,energyJKg:1000}];p.initial.fuelKg={h:1};p.initial.chargeJ=0;p.ship.modules=[{...moduleBase('gen','generator'),tankId:'h',species:'hydrogen',powerW:750,efficiency:1},{...moduleBase('cool','h2'),tankId:'h',species:'hydrogen',coolingW:750,qJKg:1000}];const a=stepModel(p.ship,initialState(p),p.environment,[],1);p.ship.modules.reverse();const b=stepModel(p.ship,initialState(p),p.environment,[],1);expect(a.state.fuelKg.h).toBeCloseTo(0);expect(a.telemetry.generatorW).toBeCloseTo(500);expect(a.telemetry.h2CoolingW).toBeCloseTo(500);expect(a.state.temperatureK).toBeCloseTo(b.state.temperatureK,10)});
it('radiation separates incoming and outgoing and preserves exact sigma',()=>{const p=fixture();p.ship.hullRadiationM2=1;p.environment.effectiveBackgroundK=400;const r=stepModel(p.ship,initialState(p),p.environment,[],.1);expect(SIGMA).toBe(5.670374419e-8);expect(r.telemetry.radiationNetW).toBeLessThan(0);expect(r.state.temperatureK).toBeGreaterThan(300);expect(r.telemetry.radiationOutW-r.telemetry.radiationInW).toBeCloseTo(r.telemetry.radiationNetW,8)});
it('background never drains battery, active can go below floors',()=>{const p=fixture();p.ship.modules=[{...moduleBase('bg','load'),policy:'Background',powerW:100}];const s=initialState(p);s.chargeJ=801;expect(stepModel(p.ship,s,p.environment,[{moduleId:'bg',duty:1}],1).telemetry.backgroundW).toBe(0);p.ship.modules[0].policy='Active';expect(stepModel(p.ship,s,p.environment,[{moduleId:'bg',duty:1}],1).state.chargeJ).toBe(701)});
it('finite buffer and electrical-starved thermoinverter cannot provide free cooling',()=>{const p=fixture();p.ship.modules=[{...moduleBase('buf','buffer'),capacityJ:10,coolingW:100}];const r=stepModel(p.ship,initialState(p),p.environment,[],1);expect(r.state.buffersJ.buf).toBeCloseTo(10);expect(r.telemetry.bufferAbsorbW).toBeCloseTo(10);p.ship.modules=[{...moduleBase('ti','thermoinverter'),coolingW:100,areaM2:1e4}];const s=initialState(p);s.chargeJ=0;expect(stepModel(p.ship,s,p.environment,[],1).telemetry.tiCoolingW).toBe(0)});
it('thermal hysteresis stops at boundary and restarts only inside corridor',()=>{const p=fixture();p.ship.modules=[{...moduleBase('laser','load'),powerW:100,gate:{low:150,high:310,restartLow:180,restartHigh:305,workHigh:307}}];const s=initialState(p);s.temperatureK=310;const a=stepModel(p.ship,s,p.environment,[{moduleId:'laser',duty:1}],1);expect(a.telemetry.deliveredW).toBe(0);a.state.temperatureK=306;expect(stepModel(p.ship,a.state,p.environment,[{moduleId:'laser',duty:1}],1).telemetry.deliveredW).toBe(0);a.state.temperatureK=304;expect(stepModel(p.ship,a.state,p.environment,[{moduleId:'laser',duty:1}],1).telemetry.deliveredW).toBe(100)});
