import {createServer} from 'vite';
import {writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const server=await createServer({configFile:false,server:{middlewareMode:true,hmr:false}});
const {presets,moduleBase,markEdits}=await server.ssrLoadModule('/src/catalog/presets.ts');
const {validateRunSpec}=await server.ssrLoadModule('/src/catalog/schema.ts');
const {createRun,runChunk}=await server.ssrLoadModule('/src/runner/run.ts');await server.close();
function fixture(dt){const p=structuredClone(presets[0]);p.ship.heatCapacityJK=100;p.ship.dryMassKg=1;p.ship.thermalMaterials=[{id:'dry',massKg:1,cpJKgK:100,contents:'dry'}];p.ship.hullRadiationM2=.01;p.ship.hullPowerW=250;p.ship.chargeEfficiency=1;p.ship.dischargeEfficiency=1;p.ship.accumulators=[{id:'a',capacityJ:100}];p.initial.chargeJ=0;p.initial.temperatureK=490;p.ship.tanks=[{id:'d',species:'diesel',capacityKg:10,energyJKg:1000,gate:{low:100,workLow:120,restartLow:110,restartHigh:480,workHigh:450,high:500}}];p.initial.fuelKg={d:10};p.initial.buffersJ={};p.ship.modules=[{...moduleBase('g','generator'),tankId:'d',species:'diesel',powerW:250,efficiency:.5,exportFraction:0,pathEfficiency:1}];p.environment.effectiveBackgroundK=100;p.environment.solarFluxWm2=0;p.environment.directHeat=[];p.environment.energyInputs=[];p.durationSeconds=20;p.stepSeconds=dt;p.scenario.phases=[{id:'idle',action:'idle',durationSeconds:20,duty:0}];p.scenario.repeat=false;markEdits(p);const valid=validateRunSpec(p);assert.ok(valid.ok,JSON.stringify(valid));return p}
const runs=[];for(const dt of [20,10,.001]){const p=fixture(dt),run=createRun('peak-'+dt,p),integrated={};let peakEndStateK=p.initial.temperatureK;while(!run.done){const previous=run.state.timeSeconds;runChunk(run,1);const elapsed=run.state.timeSeconds-previous;if(elapsed>0){for(const[k,v]of Object.entries(run.last))if(k.endsWith('W'))integrated[k]=(integrated[k]??0)+v*elapsed;peakEndStateK=Math.max(peakEndStateK,run.state.temperatureK)}}runs.push({baseDt:dt,admittedValidSpec:true,ticks:run.metrics.ticks,finalT:run.state.temperatureK,maxTemperatureMetricK:run.metrics.maxTemperatureK,peakEndStateK,fuelRemainingKg:run.state.fuelKg.d,energyResidualJ:run.metrics.energyResidualJ,integrated,events:run.events.items().filter(e=>e.kind.startsWith('thermal')),telemetryPeakFields:Object.keys(run.last).filter(k=>/max|peak/i.test(k))})}
const [coarse,half,fine]=runs;const peakHalfRelative=Math.abs(coarse.maxTemperatureMetricK-half.maxTemperatureMetricK)/half.maxTemperatureMetricK,peakRefinedRelative=Math.abs(coarse.maxTemperatureMetricK-fine.maxTemperatureMetricK)/fine.maxTemperatureMetricK;const radiationHalfRelative=Math.abs(coarse.integrated.radiationNetW-half.integrated.radiationNetW)/half.integrated.radiationNetW,radiationFineRelative=Math.abs(coarse.integrated.radiationNetW-fine.integrated.radiationNetW)/fine.integrated.radiationNetW;const result={id:'QB1/P13 within-base-dt tankstop peak then cooling',expected:'max temperature captures physical ~500K tankstop peak; nonlinear half-step peak relative<=0.001',result:peakHalfRelative<=.001&&peakRefinedRelative<=.001?'PASS':'FAIL',peakHalfRelative,peakRefinedRelative,radiationHalfRelative,radiationFineRelative,runs};writeFileSync(new URL('./peak-cycle.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
